### PR TITLE
Fix race condition in service manifest fetching

### LINKED ISSUE #2803: Reconciled columns not being draggable to item inputs in Wikidata schema
**Describe the bug**

In some situations, reconciled columns cannot be dragged and dropped to inputs that expect Wikidata entities.

**To Reproduce**
The exact steps are not clear to me, but this can be observed in the following screencast at 40:00:
https://www.twitch.tv/videos/659297903

**Desktop:**
 - OS: Windows
 - Browser Version: Firefox
 - JRE or JDK Version: 

**OpenRefine :**
 - Version 3.3

### PR DESCRIPTION
**Pull request by wetneb**
Fixes #2803

### CODE REVIEW

File: extensions/wikidata/module/scripts/dialogs/schema-alignment-dialog.js [hunk 1]
```diff
@@ -148,10 +145,16 @@ SchemaAlignmentDialog.setUpTabs = function() {
 
   this._previewPanes = $(".schema-alignment-dialog-preview");
 
-  // Load the existing schema
-  this._reset(theProject.overlayModels.wikibaseSchema);
-  // Perform initial preview
-  this.preview();
+  var url = ReconciliationManager.ensureDefaultServicePresent();
```
Comment (tfmorris) [inline extensions/wikidata/module/scripts/dialogs/schema-alignment-dialog.js:148]: This is depending on Wikidata being the default reconciliation service which is true today (and this patch doesn't change this aspect of the behavior), but it seems like the Wikidata extension should know the address of its own reconciliation service.

Also, using the ensureDefaultServicePresent function to fetch this seems rather roundabout.

**Comment by wetneb** [comment]
Agreed. With this new version, the service manifest is fetched only once, at least in the situations I tested.

**Comment by wetneb** [comment]
Merging this soon to get 3.4 released unless there are any concerns.
