### PR TITLE
Widen scrutinizer regex pattern - fixes #5656 

### LINKED ISSUE #5656: Wikimedia Commons Wikibase not detecting non-Latin script characters
I've been trying to upload a batch of files that have names containing both Latin and [Odia](https://en.wikipedia.org/wiki/Odia_script) characters. For instance, Wikimedia Commons allows filenames with Odia characters (for instance, this file](https://commons.wikimedia.org/wiki/Category:Audio_files_created_using_Kathabhidhana), but OpenRefine does not. See the screenshot of the error I see below. cc @wetneb

### To Reproduce
1. Create a file with a file name such as "ଫାଇଲ.wav" (that's a WAVE file with a filename with in the Odia script)
2. Try to upload to Wikimedia Commons using OpenRefine. It fails at the Wikibase (Upload edits to Wikibase)

### Current Results

It fails (see below)

OpenRefine-issue-with-Odia

### Expected Behavior

The upload should normally happen, just like any other file.

### Versions
 - Operating System: MacOS
 - Browser Version: Brave 1.46.171
 - JRE or JDK Version: 
 - OpenRefine: 3.7

### Datasets

1. [Sample dataset containing the same files I was trying to upload](https://drive.google.com/drive/u/0/folders/1lyg_63oZCd7fIwWFvqU4v0AwKOIHK8FQ)

### PR DESCRIPTION
**Pull request by santi4o**
Fixes #5656 

Hi there!
I've been working on the issue, thanks for your help in the issue thread

Changes proposed in this pull request:
- I updated the regex to only disallow control characters, \\p{Cc} will match control characters (ranges 0x00-0x1F and 0x7F-0x9F)
- I updated the validation for the file name length in bytes, encoded as UTF-8
- I updated the tests, adding some that should raise warnings and disabling testInvalidCharactersInFilenameVerticalBar and testInvalidCharactersInFilenameHTMLEscaped

Please let me know what you think

### CODE REVIEW

File: extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizer.java [hunk 1]
```diff
@@ -78,15 +78,20 @@ public void scrutinize(MediaInfoEdit edit) {
...
+                if (utf8Bytes.length > maxFileNameBytes) {
+                    QAWarning issue = new QAWarning(fileNameTooLongType, null,
+                            QAWarning.Severity.CRITICAL, 1);
+                    issue.setProperty("example_filename", fileName);
+                    // This is only accurate for 1 byte characters
+                    issue.setProperty("max_length", Integer.toString(maxFileNameBytes));
+                    addIssue(issue);
+                }
+            } catch (UnsupportedEncodingException e) {
+                e.printStackTrace();
```
Comment (wetneb) [inline extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizer.java:94]: I'd remove this `e.printStackTrace()` because it would be printed once for each row every time the issues are refreshed. I think it's safe to just ignore this exception altogether because if UTF-8 is not supported on the system we have bigger problems than not being able to report a quality assurance warning.

**Review by wetneb — COMMENTED** [review]
Very nice, thank you! Perhaps it would be worth adding a test showing that the filename mentioned in the issue ("ଫାଇଲ.wav") is accepted.

File: extensions/wikibase/tests/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizerTest.java [hunk 2]
```diff
@@ -67,7 +67,67 @@ public void testLongFileName() throws IOException, MediaWikiApiErrorException {
...
+    public void testInvalidCharactersInFilenameBackspace() throws IOException, MediaWikiApiErrorException {
+        MediaInfoEdit edit = new MediaInfoEditBuilder(TestingData.newMidA)
+                .addFileName("Backspaces (\b) are not allowed.png")
+                .build();
+
+        scrutinize(edit);
+        assertWarningsRaised(FileNameScrutinizer.invalidCharactersInFileNameType);
+    }
+
+    @Test(enabled = false) // Vertical bars should be allowed
```
Comment (wetneb) [inline extensions/wikibase/tests/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizerTest.java:130]: Where did you see that vertical bars should be allowed? I just tried uploading a file to Commons with a vertical bar and it is refused.

File: extensions/wikibase/tests/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizerTest.java [hunk 3]
```diff
@@ -77,7 +137,7 @@ public void testInvalidCharactersInFilenameVerticalBar() throws IOException, Med
         assertWarningsRaised(FileNameScrutinizer.invalidCharactersInFileNameType);
     }
 
-    @Test
+    @Test(enabled = false) // HTML escaped entities should be allowed
```
Comment (wetneb) [inline extensions/wikibase/tests/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizerTest.java:140]: Same here - I just tried uploading something with this filename and it fails with the error:
`This title is invalid. Make sure to remove characters like square brackets, colons, slashes, comparison operators, pipes and curly brackets.`

**Review by wetneb — COMMENTED** [review]
It looks like the regex might be a bit too wide now, see below.

**Comment by santi4o** [comment]
You're right, my bad. I read in the issue comments a possible solution involving only disallowing control characters. I was able to reproduce the issue and only tested directly in OpenRefine with Odia-script file names.
This is what I found on [Language, character set and extension
](https://commons.wikimedia.org/wiki/Commons:File_naming): "Avoid "funny" symbols (control characters, unneeded punctuation, etc.) that might be significant in future wiki markup. It is a good idea to stick to [graphemic](https://en.wiktionary.org/wiki/graphemic) characters, numbers, underscore (space), ASCII hyphen/minus/dash, plus, and period (dot)." 
I will leave an update. Thank you

**Comment by wetneb** [comment]
Hi @santi4o, are you still working on this? I think you are nearly there and it would be amazing to fix this!

**Review by wetneb — APPROVED** [review]
