### PR TITLE
Fix reconciliation result deserialization

### LINKED ISSUE #1876: Guess reconciliation type command does not work since Jackson migration
This is probably due to invalid queries being made or incorrect parsing of the results.

### PR DESCRIPTION
**Pull request by wetneb**
Closes #1876.

### CODE REVIEW

File: main/tests/server/src/com/google/refine/tests/model/recon/StandardReconConfigTests.java [hunk 1]
```diff
@@ -172,4 +173,17 @@ public void deserializeColumnDetail() throws JsonParseException, JsonMappingExce
     	ColumnDetail cd = ParsingUtilities.mapper.readValue(uiJson, ColumnDetail.class);
     	TestUtils.isSerializedTo(cd, backendJson);
     }
+    
+    @Test
+    public void deserializeReconResult() throws JsonParseException, JsonMappingException, IOException {
+    	String json = "{\"score\":100.0,"
+    			+ "\"match\":false,"
+    			+ "\"type\":["
```
Comment (jackyq2015) [inline main/tests/server/src/com/google/refine/tests/model/recon/StandardReconConfigTests.java]: should be "types"?

Comment (wetneb) [reply main/tests/server/src/com/google/refine/tests/model/recon/StandardReconConfigTests.java]: No, the JSON format implement with `org.json` used `type`, not `types`. We need to keep this format so that reconciliation services still work.
