### PR TITLE
ci: Switch locale to French for Java tests

### LINKED ISSUE #7054: Tests not passing in a non-English locale
We have again Java test cases which do not pass when executed on a computer with a non-English locale:

```

[ERROR] Failures: 
[ERROR]   CrossTests.crossFunctionNonLiteralValue:397 expected [cross expects a cell or value, a project name to look up (optional), and a column name in that project (optional)] but found [cross attend une cellule ou une valeur, un nom de projet à rechercher (facultatif) et un nom de colonne dans ce projet (facultatif)]
[ERROR]   CrossTests.crossFunctionNullParams:402 expected [cross expects a cell or value, a project name to look up (optional), and a column name in that project (optional)] but found [cross attend une cellule ou une valeur, un nom de projet à rechercher (facultatif) et un nom de colonne dans ce projet (facultatif)]
[ERROR]   ZipTests.testZipForParams:99 expected:<zip nécessite 2 tableaux ou plus comme arguments> but was:<zip expects 2 or more arrays as arguments>
[ERROR]   InnerHtmlTests.testInnerHtml:44 expected [innerHtml() cannot work with this 'string'. The first parameter is not an HTML Element. Please first use parseHtml(string) and select(query) prior to using this function] but found [innerHtml() ne peut pas fonctionner avec ce 'string'. Le premier paramètre nest pas un élément HTML. Veuillez dabord utiliser parseHtml(string) et select(query) avant dutiliser cette fonction]
[ERROR]   WholeTextTests.testWholeText:44 expected [wholeText() cannot work with this 'string' and failed as the first parameter is not an XML or HTML Element.  Please first use parseXml() or parseHtml() and select(query) prior to using this function] but found [wholeText() ne peut pas fonctionner avec ce 'string' et a échoué car le premier paramètre nest pas un élément XML ou HTML.    Veuillez dabord utiliser parseXml() ou parseHtml() et select(query) avant dutiliser cette fonction.]
[ERROR]   XmlTextTests.testXmlText:44 expected [xmlText() cannot work with this 'string' and failed as the first parameter is not an XML or HTML Element.  Please first use parseXml() or parseHtml() and select(query) prior to using this function] but found [xmlText() ne peut pas fonctionner avec ce 'string' et a échoué car le premier paramètre nest pas un élément XML ou HTML.    Veuillez dabord utiliser parseXml() ou parseHtml() et select(query) avant dutiliser cette fonction.]
[ERROR]   ForNonBlankTests.serializeForNonBlank:39 Objects above are not equal as JSON strings.
[ERROR]   IfTests.serializeIf:39 Objects above are not equal as JSON strings.
[ERROR]   IsBlankTests.serializeIsBlank:39 Objects above are not equal as JSON strings.
[ERROR]   IsEmptyStringTests.serializeIsEmptyString:39 Objects above are not equal as JSON strings.
[ERROR]   IsErrorTests.serializeIsError:39 Objects above are not equal as JSON strings.
[ERROR]   IsNonBlankTests.serializeIsNonBlank:39 Objects above are not equal as JSON strings.
[ERROR]   IsNotNullTests.serializeIsNotNull:39 Objects above are not equal as JSON strings.
[ERROR]   IsNullTests.serializeIsNull:39 Objects above are not equal as JSON strings.
[ERROR]   IsNumericTests.serializeIsNumeric:39 Objects above are not equal as JSON strings.
[ERROR]   WithTests.serializeWith:39 Objects above are not equal as JSON strings.
```

It would be worth:
* changing the locale in the CI to a non-English ("non-default") one to avoid that
* or somehow finding a way to reliably configure tests so that they always execute in an English locale
* or changing the tests so that they don't depend on the locale

### PR DESCRIPTION
**Pull request by wetneb**
Fixes #7054.
I expect the CI to fail first, and require adapting the tests.

### CODE REVIEW

**Comment by wetneb** [comment]
I have set the locale to French because it's complete, so it will pick up locale-dependent tests better than incomplete languages (where falling back to English is the norm).

File: main/src/com/google/refine/operations/recon/ReconCopyAcrossColumnsOperation.java [hunk 1]
```diff
@@ -195,6 +195,6 @@ public boolean visit(Project project, int rowIndex, Row row) {
 
     @Override
     protected String getBriefDescription(Project project) {
-        return OperationDescription.recon_copy_across_columns_brief(_fromColumnName, StringUtils.join(_toColumnNames));
+        return OperationDescription.recon_copy_across_columns_brief(_fromColumnName, StringUtils.join(_toColumnNames, ", "));
```
Comment (wetneb) [inline main/src/com/google/refine/operations/recon/ReconCopyAcrossColumnsOperation.java:198]: This was a missing separator I noticed while adapting the tests. Without this, the column names are joined without any separator.

File: modules/grel/src/test/java/com/google/refine/grel/controls/ForNonBlankTests.java [hunk 2]
```diff
@@ -1,41 +0,0 @@
...
-import org.testng.annotations.Test;
-
-import com.google.refine.util.TestUtils;
-
-public class ForNonBlankTests {
-
-    @Test
-    public void serializeForNonBlank() {
-        String json = "{\"description\":\"Evaluates expression o. If it is non-blank, binds its value to variable name v, evaluates expression eNonBlank and returns the result. Otherwise (if o evaluates to blank), evaluates expression eBlank and returns that result instead.\",\"params\":\"expression o, variable v, expression eNonBlank, expression eBlank\",\"returns\":\"Depends on actual arguments\"}";
-        TestUtils.isSerializedTo(new ForNonBlank(), json);
```
Comment (wetneb) [inline modules/grel/src/test/java/com/google/refine/grel/controls/ForNonBlankTests.java:39]: I have deleted those serialization tests because the serialization of GREL controls is just defined by the interface, so those tests don't really test anything except for the exact values of those documentation strings, which isn't very useful.

**Comment by wetneb** [comment]
Merging to avoid conflicts with #7061.
