### PR TITLE
Use Apache HTTP Commons for Fetch URL

### LINKED ISSUE #1410: Fetch URLs should follow redirections
Apparently, HTTP redirections are not followed by the URL fetcher: they probably should.

### LINKED ISSUE #1904: Mock the Url Fetching Tests (because they fail too often as not reachable)
**Describe the bug**
When running `refine test` the UrlFetchingTests often fail.

**To Reproduce**
1. refine test

**Current Results**
[ERROR] Tests run: 558, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 60.912 s <<< FAILURE! - in TestSuite
[ERROR] testInvalidUrl(com.google.refine.tests.operations.column.ColumnAdditionByFetchingURLsOperationTests)  Time elapsed: 5.006 s  <<< FAILURE!
java.lang.AssertionError: expected [false] but found [true]
        at com.google.refine.tests.operations.column.ColumnAdditionByFetchingURLsOperationTests.testInvalidUrl(ColumnAdditionByFetchingURLsOperationTests.java:226)

**Expected behavior**
URL tests should be mocked against an http server and pass, and not depend on real sites availability.

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - JRE or JDK Version: JDK 1.8.0_181 or JDK 11.0.1

**OpenRefine (please complete the following information):**
 - Version: Trunk

### LINKED ISSUE #2680: Network tests being silently skipped
One of the HTTP tests relies on the external endpoint `http://headers.jsontest.com` but if this service is overquota and returning 503s (like it is today), the related tests are silently skipped.

https://github.com/OpenRefine/OpenRefine/blob/5351e9f41c9188006f156c27eadbd6a838cb152d/main/tests/server/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperationTests.java#L285-L298

We should figure out a better way to do this, which doesn't rely on an unreliable external service. One possibility would be to self-host the servlet https://github.com/jsontest/jsontest

### PR DESCRIPTION
**Pull request by tfmorris**
* Fixes #1410 by virtue of HTTP Commons having built-in support for redirects. It also supports retries, gzip decompression, and a bunch of other stuff out of the box.

* Replaced external network tests with mockwebserver based tests which should be faster and 100% reliable. Refactored to remove redundancy and make quicker. Fixes #2680. Fixes #1904.

* Replaces use of deprecated methods in ImportingUtilities which had already been converted to use Apache HTTP Commons for project creation.

### CODE REVIEW

File: main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java [hunk 1]
```diff
@@ -134,8 +151,34 @@ public ColumnAdditionByFetchingURLsOperation(
         _delay = delay;
         _cacheResponses = cacheResponses;
         _httpHeadersJson = httpHeadersJson;
+
+        List<Header> headers = new ArrayList<Header>();
+        if (_httpHeadersJson != null) {
+            for (HttpHeader header : _httpHeadersJson) {
+                if (header.name != null && header.name != "" && header.value != null && header.value != "") {
```
Comment (wetneb) [inline main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java:158]: Shouldn't checks like `header.name != ""` use `equals` instead?

File: main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java [hunk 2]
```diff
@@ -134,8 +151,34 @@ public ColumnAdditionByFetchingURLsOperation(
...
+        httpHeaders = headers.toArray(httpHeaders);
+
+        defaultRequestConfig = RequestConfig.custom()
+                .setConnectTimeout(30 * 1000)
+                .setConnectionRequestTimeout(30 * 1000)
+                .setSocketTimeout(10 * 1000).build();
+
+//        CredentialsProvider credsProvider = new BasicCredentialsProvider();
+//        credsProvider.setCredentials(new AuthScope(host, 443),
+//                new UsernamePasswordCredentials(user, password));
```
Comment (wetneb) [inline main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java:172]: Why is this code commented out?

**Comment by wetneb** [comment]
Thanks a lot for tackling this, of course!

File: main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java (hunk 1 above)
Comment (tfmorris) [reply main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java:158]: Yes, of course! I'll fix it.

File: main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java (hunk 2 above)
Comment (tfmorris) [reply main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java:172]: It's not part of the current functionality, so not included in the refactoring. I left it as a placeholder for future feature enhancement, but I can remove it if you think that would be cleaner.

Comment (wetneb) [reply main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java:172]: Ah yes, I thought we supported this already, but we only expose an `Authorization` header in the UI. I generally try to avoid committing commented out code, but if you want to leave it as a demo for future improvements, it could be worth explaining that intention with a comment, perhaps?

File: main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java (hunk 1 above)
Comment (tfmorris) [reply main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java]: Done.

File: main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java (hunk 2 above)
Comment (tfmorris) [reply main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java:175]: Comment added

**Comment by tfmorris** [comment]
Just in time because our Fetch URL tests are failing due to random.org taking more than 5 seconds to return a result.
