### PR TITLE
Fix templating exporter to accept closing braces in expressions

### LINKED ISSUE #3381: Broken escaping in templating export
Curly braces are used in the templating exporter to delimit expressions from the rest of the template text. Therefore if we want to use curly braces in the expressions they need to be escaped. According to the code, we are supposed to do this with `\{`, but that does not actually work.

### To Reproduce
1. First, open any project
2. Then, open the templating export dialog
3. Finally, input the following template:
```
{{"\}\}"}}
```

This is supposed to evaluate to just `}}` for each row.

### Current Results
We get `{{"\}\}"}}` instead.

### Expected Behavior
We should get `}}`

### Versions
 - Operating System: Linux
 - Browser Version: irrelevant
 - JRE or JDK Version: 11
 - OpenRefine: 3.4.1

### Additional context

Brought up while trying to document the templating exporter.

### PR DESCRIPTION
**Pull request by JohnMcGrane**
Fixes #3381

Templating is fixed according to the issue specification.

### CODE REVIEW

File: main/src/com/google/refine/templating/Parser.java [hunk 1]
```diff
@@ -33,15 +33,39 @@
...
+     * Finds the first true ending brace in a cell, ignoring escaped end braces
+     *
+     * @param expression string that will be interrogated for first true end brace
+     * @param lowIndex   index from which the interrogation will start
+     * @return index of the first true end brace
+     * CS427 Issue Link: https://github.com/OpenRefine/OpenRefine/issues/3381
+     */
+    private static int findEndBrace(final String expression, final int lowIndex) {
+        int closeBrace = expression.indexOf('}', lowIndex);
+        if (expression.charAt(closeBrace - 1) == '\\') {
```
Comment (wetneb) [inline main/src/com/google/refine/templating/Parser.java:60]: What happens if no `}` character could be found? In the case of an unfinished template, we should make sure we fail graciously.

**Review by wetneb — COMMENTED** [review]
Besides the spurious reformatting problems (which I cannot really blame you for, we should have a CI-enforced linting), this PR looks very good to me. I am just wondering about a side case, see below.

File: main/src/com/google/refine/templating/Parser.java (hunk 1 above)
Comment (JohnMcGrane) [reply main/src/com/google/refine/templating/Parser.java:60]: Hey @wetneb I just added a parsing exception in case no end brace can be found. Is that what you meant by fail graciously? If not I can go back and implement whatever you were thinking.

**Comment by wetneb** [comment]
Looks like we have some merge conflicts that should be solved before the CI can kick in.

**Comment by JohnMcGrane** [comment]
@wetneb Okay, I think this should be good to go, let me know what you think!

**Comment by JohnMcGrane** [comment]
@wetneb Okay I added back the test that I had taken out. (It was causing some build failure but I just needed to format it correctly).

**Review by wetneb — APPROVED** [review]
Thanks a lot!
