### PR TITLE
Ignore events which don't change text input - fixes #1134

### LINKED ISSUE #1134: First pagination action after applying text filter fails
After applying a text filter to a project, if you then try to go to the next/last page, the project goes to the next/last page then refreshes back to the first page of the project.

If you then try the same action it is successful.
If you update the text filter the same thing happens again.

Tested on Mac using Linux build of 2.6 RC2 on Safari 9.1.1 and Chrome 50.0.2661.102

### PR DESCRIPTION
**Pull request by tfmorris**
Fixes #1134.

### CODE REVIEW

File: main/webapp/modules/core/scripts/facets/text-search-facet.js [hunk 1]
```diff
@@ -141,9 +141,9 @@ TextSearchFacet.prototype._initializeUI = function() {
     this._elmts.input[0].value = this._query;
   }
   
-  this._elmts.input.bind("keyup change input",function(evt) {
-    // Ignore non-character keyup changes
-    if(evt.type === "keyup" && (this.value === self._query || this.value === '' && !self._query)) {
+  elmts.input.bind("keyup change input",function(evt) {
```
Comment (lisa761) [inline main/webapp/modules/core/scripts/facets/text-search-facet.js:144]: This line throws an error:



If I switch it back to `this._elmts`, it works just fine and the `next` and `last` buttons work as well.

**Comment by tfmorris** [comment]
@lisa761 Thanks for testing! Feel free to use it, if it's helpful.

File: main/webapp/modules/core/scripts/facets/text-search-facet.js (hunk 1 above)
Comment (tfmorris) [reply main/webapp/modules/core/scripts/facets/text-search-facet.js]: Fixed.
