### PR TITLE
Translate Sort link to the language of the UI

### LINKED ISSUE #2233: Translate the "Sort" link
**Describe the bug**

When a sort is made, the link "Sort" is displayed. It is not translated when the language of the UI is not english.

I suppose it could be done by editing this line 
https://github.com/OpenRefine/OpenRefine/blob/76162cfed150b32e1496bc07082302c35f56c6d7/main/webapp/modules/core/scripts/views/data-table/data-table-view.js#L152

**To Reproduce**

**Current Results**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Version: Chrome
 - JRE or JDK Version:  JRE 1.8.0_231

**OpenRefine (please complete the following information):**
 - Version :  OpenRefine 3.3 Beta

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #2233 

```
After a sort is made, the Sort link that is displayed does not
reflect to the corresponding language of the UI.

This PR adds the translation of the corresponding language
of the UI to the Sort link.
```

### CODE REVIEW

File: main/webapp/modules/core/scripts/views/data-table/data-table-view.js [hunk 1]
```diff
@@ -149,7 +149,7 @@ DataTableView.prototype._renderSortingControls = function(sortingControls) {
 
   $('<a href="javascript:{}"></a>')
   .addClass("action")
-  .text("Sort ")
+  .text($.i18n('core-views/first') + " ")
```
Comment (wetneb) [inline main/webapp/modules/core/scripts/views/data-table/data-table-view.js]: This is a good start! However it's not enough for this string to be translatable - it also needs to say the right thing :)
At the moment this will show "First" instead of "Sort", which would be quite confusing. So the identifier for the translatable string needs to be different.

Comment (jamessspanggg) [reply main/webapp/modules/core/scripts/views/data-table/data-table-view.js]: ahhh yes, that is really an obvious mistake 🤦‍♂ Have made the necessary change.
