### PR TITLE
Fixes #2316 "Match other cells with same content" keeps appearing as the default choice #2316

### LINKED ISSUE #2316: "Match other cells with same content" keeps appearing as the default choice
**Describe the bug**

When doing reconciliation, I sometimes manually match entries to Wikidata items using "Search for match". I choose the correct match but the match is applied to _all entries with the same name_ because the radio button "Match other cells with same content" is always ticked by default. Even if I change it, next time this button will again be ticked. 

**Expected behavior**
It would be very cool if I could either choose the default button in settings, or OpenRefine could remember my last choice.

**Screenshots**
Bez názvu

**Desktop**
 - OS: [Windows 10]
 - Browser Version: Chrome version 80.0.3987.106
 - OpenRefine 3.3 Beta

### PR DESCRIPTION
**Pull request by WaltonG**
Fixes #2316

Changes proposed in this pull request:
- Use a global variable to store user's choice of radio button
- Checked radio button is set by the user's previous choice
-

### CODE REVIEW

File: main/webapp/modules/core/scripts/views/data-table/cell-ui.js [hunk 1]
```diff
@@ -41,6 +41,8 @@ function DataTableCellUI(dataTableView, cell, rowIndex, cellIndex, td) {
   this._render();
 }
 
+var defaultChoice = true;
```
Comment (wetneb) [inline main/webapp/modules/core/scripts/views/data-table/cell-ui.js:44]: Since you are introducing this as a global variable, I think it would be better to use a more specific name, making it clear which choice it affects. For instance `reconMatchSilimilarCellsByDefault` or something like that.

File: main/webapp/modules/core/scripts/views/data-table/cell-ui.js [hunk 2]
```diff
@@ -360,9 +362,25 @@ DataTableCellUI.prototype._searchForMatch = function(suggestOptions) {
...
+		elmts.radioSimilar[0].setAttribute("checked", false);
+		elmts.radioOne[0].setAttribute("checked", true);
+	}
 
   var level = DialogSystem.showDialog(frame);
   var dismiss = function() {
+	  if (elmts.radioSimilar[0].checked) {
+		  defaultChoice = true;
+		  elmts.radioSimilar[0].setAttribute("checked", true);
+		  elmts.radioOne[0].setAttribute("checked", false);
```
Comment (wetneb) [inline main/webapp/modules/core/scripts/views/data-table/cell-ui.js:376]: It is not clear to me why the two lines above are needed - why do you need to update the DOM at this stage? (similarly below)

**Review by wetneb — COMMENTED** [review]
Thank you, I think this is on the right track!

File: main/webapp/modules/core/scripts/views/data-table/cell-ui.js (hunk 1 above)
Comment (WaltonG) [reply main/webapp/modules/core/scripts/views/data-table/cell-ui.js:44]: Well noted

File: main/webapp/modules/core/scripts/views/data-table/cell-ui.js (hunk 2 above)
Comment (WaltonG) [reply main/webapp/modules/core/scripts/views/data-table/cell-ui.js:376]: Actually I think its not needed since the users choice has been stored in the global variable and the DOM should be updated using the global variable value when the reconciliation match dialog is opened. 
Let me work on it an see the outcome

**Comment by elroykanye** [comment]
I don't know what happened to the workflows  @WaltonG but I guess it is all good now. I had to cancel and rerun.

**Comment by WaltonG** [comment]
> I don't know what happened to the workflows @WaltonG but I guess it is all good now. I had to cancel and rerun.
This PR is fine. The issue was on PR #4673  The check have failed with null poniter exception. Can you check it out

File: main/webapp/modules/core/scripts/views/data-table/cell-ui.js [hunk 3]
```diff
@@ -360,9 +362,20 @@ DataTableCellUI.prototype._searchForMatch = function(suggestOptions) {
...
   elmts.cancelButton.html($.i18n('core-buttons/cancel'));
+  
+	if (!reconMatchSilimilarCellsByDefault) {
+		elmts.radioSimilar[0].setAttribute("checked", false);
+		elmts.radioOne[0].setAttribute("checked", true);
+	}
 
   var level = DialogSystem.showDialog(frame);
   var dismiss = function() {
+	  if (elmts.radioSimilar[0].checked) {
```
[the remark this answers is not in the document]
Comment (WaltonG) [reply main/webapp/modules/core/scripts/views/data-table/cell-ui.js:373]: I think its logical because if radioSimilar is checked it automatically implies the radioOne is uchecked and vice versa.
Thanks

**Review by antoine2711 — APPROVED** [review]
@WaltonG 👍 Good work. This is complete for me. @wetneb will merge soon.

Regards, Antoine

**Comment by WaltonG** [comment]
@antoine2711 👍

**Review by wetneb — APPROVED** [review]
Thank you!
