### PR TITLE
fix: Remove spurious recon logo warnings

### LINKED ISSUE #7021: Console messages about missing reconciliation logos
### To Reproduce
1. First, open a project with reconciled columns, where the service doesn't offer a logo

### Current Results

In the browser console:
```
Invalid logo URL supplied by service null project-bundle.js:47001:13
Invalid logo URL supplied by service https://wikidata.reconci.link/en/api project-bundle.js:57862:13
Invalid logo URL supplied by service null project-bundle.js:57862:13
Invalid logo URL supplied by service https://wikidata.reconci.link/en/api 2 project-bundle.js:57862:13
Invalid logo URL supplied by service null 2 project-bundle.js:57862:13
```

### Expected Behavior
No warnings

### Screenshots

image

### Versions
 - master branch

### PR DESCRIPTION
**Pull request by wetneb**
Closes #7021.

### CODE REVIEW

File: main/webapp/modules/core/scripts/views/data-table/column-header-ui.js [hunk 1]
```diff
@@ -72,29 +72,31 @@ DataTableColumnHeaderUI.prototype._render = function() {
...
-      img.appendTo(elmts.serviceLogoContainer.show());
+  if (serviceUrl) {
+    try {
+      var service = null;
+      var serviceLogo = null;
+      if (new URL(serviceUrl)) {
+        service = ReconciliationManager.getServiceFromUrl(serviceUrl);
+      }
+      if (service) {
+        serviceLogo = service.logo;
```
Comment (Abbe98) [inline main/webapp/modules/core/scripts/views/data-table/column-header-ui.js:86]: Shouldn't there be a `new URL()` check here just as in `schema-alignment.js`?

Comment (wetneb) [reply main/webapp/modules/core/scripts/views/data-table/column-header-ui.js:86]: Sure, I've added it underneath as at this stage `serviceLogo` can still be `undefined`.

**Review by Abbe98 — APPROVED** [review]
