### PR TITLE
Use real TSV exporter/importer. Fixes #2071

### LINKED ISSUE #2071: TSV export escapes double quotes (") unnecessarily
I export a project in tab separated values. In the resulting TSV file I found duplicates double quotes. OR seems to escape the quotes, but I don't want this behavior

### To Reproduce

Export to TSV a project containing cell values with double quote characters (") in them.

### Current Results
Cells which contain double quote characters (") are wrapped in quotes and have the internal quotes escaped, even though the separate value is \t, not ". e.g. the cell value 'comme "braille mental"' (without the single quotes) gets exported as '"comme ""braille mental"""'

### Expected behavior
Quote characters should be left untouched and only embedded TAB, LF, & CR characters should be escaped (\t, \n, \r).

### Screenshots
In my project
image

In my tsv
image

**Desktop**
 - OS: win10
 - Browser Version: Chrome
 - JRE or JDK Version:1.8.0_211

**OpenRefine**
 - Version : OR 3.1

### PR DESCRIPTION
**Pull request by tfmorris**
Fixes #2071

Changes proposed in this pull request:
- Don't escape quotes when writing TSV format
- Escape \n and \r as is common practice
- Adjust tests to match desired behavior (they were written over a decade ago to match the observed behavior of the CSV library rather than the industry practice)
- Switch to real TSV parser for case where \t is the separator and there are no "exotic" options (so users can still use the CSV importer with \t if they need fancy quote support or something similar)
- Add test for unescaping of \t, \n, \r

### CODE REVIEW

File: main/src/com/google/refine/importers/SeparatorBasedImporter.java [hunk 1]
```diff
@@ -136,21 +142,28 @@ public void parseOneFile(
...
-        format.setQuote(quote);
-        format.setLineSeparator("\n");
-        settings.setIgnoreLeadingWhitespaces(false);
-        settings.setIgnoreTrailingWhitespaces(false);
-        if (strictQuotes) {
-            settings.setUnescapedQuoteHandling(UnescapedQuoteHandling.RAISE_ERROR);
+        AbstractParser parser;
+        if (tsv) {
+            TsvParserSettings settings = new TsvParserSettings();
+            settings.setMaxCharsPerColumn(256 * 1024); // TODO: Perhaps use a lower default and make user configurable?
```
Comment (wetneb) [inline main/src/com/google/refine/importers/SeparatorBasedImporter.java:148]: I think it makes sense to have different default settings for TSV vs CSV but with this change we'd be ignoring quote settings (the quote character, and the setting to preserve leading/trailing whitespace), as soon as the user uses tabs as separator, right?
As a user I'd find it confusing to see that options I am offered aren't actually honored.

Would it not be preferable to integrate this logic in `createParserUIInitializationData`, so that the default options for those parameters are set to sensible values, and then we can stick to passing them to `CsvFormat` regardless of the separator, as it used to be?

**Review by wetneb — COMMENTED** [review]
Thanks! I have to say I find it hard to judge whether people prefer escaping to quoting… Is this mandated by some RFC or other type of spec? Is this well understood by Excel/LibreOffice/Google Sheets?

I have no strong feelings on this but I suspect this can be a disruptive change for some folks so better err on the side of caution.

File: main/src/com/google/refine/importers/SeparatorBasedImporter.java (hunk 1 above)
Comment (wetneb) [reply main/src/com/google/refine/importers/SeparatorBasedImporter.java:148]: Ok, I see the options are honored, thanks for the clarification. I think the UI is fine as such.

**Review by wetneb — APPROVED** [review]
