### PR TITLE
(I#1418 I#3719 I#3277) Fix projectID remains in workspace.json after deleting a project

### LINKED ISSUE #1418: id of deleted project will be kept in workspace.json
I have a project that makes use of another project (as mapping table). After the processing (i.e. application of the mapping rules (JSON history) + exporting the result), I'm deleting both projects. Only the id of the main project will be kept in workspace.json. The auxiliary project (with the mapping table) disappears as expected. When I restart OpenRefine, it tries to recover the project whose id still has been left in the workspace.json. When I try to reimport both projects and do the processing afterwards, then the mapping table won't be applied. So I guess it has something to do with the incomplete removal (and the unsuccessful recovery after OpenRefine restart) of the main project.
My current workaround is that I'll give the main project each time a new name at import.
  
tested with OpenRefine 2.7 and 2.8

### PR DESCRIPTION
**Pull request by WaltonG**
Fixes #1418 #3719 #3277 

Changes proposed in this pull request:
- When there is no project in the workspace after deleting the only existing project, set the projectIDs property in the workspace.json file to empty.

### CODE REVIEW

**Comment by antoine2711** [comment]
@wetneb: I'll leave it to you to review once @WaltonG is ready.

**Comment by WaltonG** [comment]
The PR is ready for review

**Comment by wetneb** [comment]
Very nice! It looks like you have found the cause of the bug indeed :)
One thing I wonder about, though, is that with this change we will be saving the workspace over and over as long as it stays empty, which is perhaps not a big deal (saving an empty workspace does not cost much) but is perhaps not so elegant. More generally, when reading this `saveNeeded()` method, it might not be immediately obvious to another developer why an empty workspace always needs saving (so the check is likely to be removed by someone else in the future).
To avoid that, I would propose two things:
* Perhaps introduce a `projectRemoved` boolean flag, which would be set to true when we delete a project, and reset to false when the workspace is saved. This would have two benefits: avoid the repeated saving of empty workspaces, and also cater for the case where a project was removed but the workspace is not empty either
* Add a unit test (with a reference to the GitHub issues mentioned in your PR) to demonstrate the behaviour

**Comment by WaltonG** [comment]
Sure will work on the proposals

**Comment by WaltonG** [comment]
Unit test is needed for the integration test to pass. Working on it.

**Comment by WaltonG** [comment]
> Very nice! It looks like you have found the cause of the bug indeed :) One thing I wonder about, though, is that with this change we will be saving the workspace over and over as long as it stays empty, which is perhaps not a big deal (saving an empty workspace does not cost much) but is perhaps not so elegant. More generally, when reading this `saveNeeded()` method, it might not be immediately obvious to another developer why an empty workspace always needs saving (so the check is likely to be removed by someone else in the future). To avoid that, I would propose two things:
> 
> * Perhaps introduce a `projectRemoved` boolean flag, which would be set to true when we delete a project, and reset to false when the workspace is saved. This would have two benefits: avoid the repeated saving of empty workspaces, and also cater for the case where a project was removed but the workspace is not empty either
> * Add a unit test (with a reference to the GitHub issues mentioned in your PR) to demonstrate the behaviour

The unit test seems quite complicated as it involves quite a number of methods, creating a project, saving the project, deleting the project, reading the workspace file. Let me see how it will workout.

File: main/src/com/google/refine/io/FileProjectManager.java [hunk 1]
```diff
@@ -288,15 +290,20 @@ protected void saveWorkspace() {
                 file.renameTo(oldFile);
             }
 
+            if (oldFile.exists() && _projects.isEmpty()) {
+                oldFile.delete();
+            }
```
Comment (wetneb) [inline main/src/com/google/refine/io/FileProjectManager.java:295]: It is not clear to me why we need to delete the old file in this case, can you explain a bit more?

Comment (WaltonG) [reply main/src/com/google/refine/io/FileProjectManager.java:295]: When a workspace is saved after removing a projectID its previous state is stored in wospace.old.json. When the only existing project is removed and the workspace is saved, workspace.old.json while retain the deleted projectID. 
On restarting the server, an empty project directory for the projectID  in workspace.old.json is created and this brings back the bug we are fixing.

Comment (wetneb) [reply main/src/com/google/refine/io/FileProjectManager.java:295]: But why is the empty project directory leftover? Should we not rather delete that directory instead of deleting `workspace.old.json`?

Comment (WaltonG) [reply main/src/com/google/refine/io/FileProjectManager.java:295]: The project directory is actually deleted as expected but when the server is restarted projects are loaded from :https://github.com/OpenRefine/OpenRefine/blob/1cb874819284ae21a43117decc5f10297a6092a7/main/src/com/google/refine/io/FileProjectManager.java#L361-L372

Since `workspace.old.json` has a projectID and there is no existing project directory for it an empty project directory is created

File: main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java [hunk 2]
```diff
@@ -92,4 +102,28 @@ public void saveReloadMultinationalCharacter() throws IOException {
...
+        manager.saveWorkspace();
+        System.out.println(workspaceFile.getPath());
+        System.out.println(ParsingUtilities.inputStreamToString(f));
+
+        manager = new FileProjectManagerStub(workspaceFile);
+        manager.deleteProject(5555);
+        System.out.println(workspaceFile.getPath());
+        System.out.println(ParsingUtilities.inputStreamToString(f));
+    }
 }
```
Comment (WaltonG) [inline main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java:129]: @elroykanye Can I get some assistance here. Seems am stuck.

File: main/src/com/google/refine/io/FileProjectManager.java (hunk 1 above)
Comment (wetneb) [reply main/src/com/google/refine/io/FileProjectManager.java:295]: Ah, then that sounds like the `loadFromFile` method incorrectly considers that loading `workspace.json` failed if it did not load any project: it should instead recognize that it successfully loaded an empty workspace, no?

Comment (WaltonG) [reply main/src/com/google/refine/io/FileProjectManager.java:295]: Correct. That should be the case

File: main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java (hunk 2 above)
Comment (elroykanye) [reply main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java:123]: Hi @WaltonG , let me check this out and give you feedback.

Comment (elroykanye) [reply main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java:123]: Similar to how you created a temporary workspace file, I think you should do same for the project file and call this `manager.saveToFile()` for it.

Am I on track with you?

Comment (WaltonG) [reply main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java:123]: Sure. Let me look into that

File: main/src/com/google/refine/io/FileProjectManager.java (hunk 1 above)
Comment (wetneb) [reply main/src/com/google/refine/io/FileProjectManager.java:295]: Hi @WaltonG, is this still needed after your changes then?

Comment (WaltonG) [reply main/src/com/google/refine/io/FileProjectManager.java:295]: Hi @wetneb I don't think it's needed. Let me confirm

Comment (WaltonG) [reply main/src/com/google/refine/io/FileProjectManager.java:295]: Hi @wetneb, I have confirmed that loading of projects from workspace.temp.json and workspace.old.json is not required

Comment (wetneb) [reply main/src/com/google/refine/io/FileProjectManager.java:295]: Hmm, that is curious! Intuitively, this fallback mechanism should still be useful if `workspace.json` disappeared (after a failed save, perhaps).
I would expect that this code to load from `workspace.temp.json` and `workspace.old.json` stays, but the return value of `loadWorkspace` is not whether a project was found or not, but rather whether the loading of the workspace succeeded or not (which is different, since it is possible to successfully load an empty workspace). This is what I have tried to explain in my comment above - is this new comment any clearer?

Comment (WaltonG) [reply main/src/com/google/refine/io/FileProjectManager.java:295]: Sure the comment is clearer and a fallback mechanism is actually needed. With that in mind am rechecking if deleting `workspace.old.json`  is still needed.

Comment (WaltonG) [reply main/src/com/google/refine/io/FileProjectManager.java:295]: > Hmm, that is curious! Intuitively, this fallback mechanism should still be useful if `workspace.json` disappeared (after a failed save, perhaps).

Considering this scenario, when a project directory is deleted but saving the workspace  failed then the fallback mechanism will reference a non existing project directory. In the following code is it ok to move `saveWorkspace()` to the synchronized block

https://github.com/OpenRefine/OpenRefine/blob/f151be913b5d7de25b312a48300080190e68a605/main/src/com/google/refine/io/FileProjectManager.java#L327-L338

File: main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java [hunk 3]
```diff
@@ -92,4 +101,35 @@ public void saveReloadMultinationalCharacter() throws IOException {
...
+     */
+    @Test
+    public void deleteProjectWithoutSavingWorkspace() throws IOException {
+        FileProjectManager manager = new FileProjectManagerStub(workspaceDir);
+        manager.saveToFile(workspaceFile);
+        manager.deleteProject(5555);
+
+        InputStream inputStream = new FileInputStream(workspaceFile);
+        JsonObject json = JSON.parse(inputStream);
+        assertFalse(json.get("projectIDs").getAsArray().isEmpty());
```
Comment (wetneb) [inline main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java:117]: I am not sure about this test: your comment above says "deleting the only existing project without saving the workspace will *not* remove the projectID from workspace.json" but in the test you do assert that the array is empty… That seems inconsistent, no? I think the test below should actually be sufficient, no?

Comment (WaltonG) [reply main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java:117]: > but in the test you do assert that the array is empty… That seems inconsistent, no?

That is not the case. The test uses `assertFalse`  on `isEmpty()` which confirms that the array is not empty

> I think the test below should actually be sufficient, no?

Thats true since it confirms that deleting and saving the workspace removes projectID from wokspace.json thus fixing the issues

Comment (wetneb) [reply main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java:117]: Ah thanks, looks like I was not really awake :-D
Sounds good, then let's only keep the second test.
