### PR TITLE
 hyperlink issue  fixed and  tests added

### LINKED ISSUE #2519: Hyperlink is created for cell value even when invalid and text datatype is choosen
**Describe the bug**
Hyperlink is created for cell value, even when text is specified as the datatype.

**To Reproduce**
1. Edit a cell's value
2. Choose datatype: Text
3. Paste the following text exactly (includes whitespace):
```
https://www.wikidata.org/wiki/Property:P670 https://www.wikidata.org/wiki/Property:P669 are now mapped to https://schema.org/streetAddress via https://www.wikidata.org/wiki/Property:P2235
```

4. Click Apply

**Current Results**
Notice that cell value is shown completely as a clickable hyperlink rather than just text.

**Expected behavior**
The cell's value should be rendered with only those pieces which represent valid URLs hyperlinked. For the example above, there should be four hyperlinks with unlinked text " are now mapped to " and " via " between them.

Browsers now have native support for URL detection and we should take advantage of that.  See comment https://github.com/OpenRefine/OpenRefine/issues/2519#issuecomment-612645821

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: JDK8

**OpenRefine (please complete the following information):**
 - Version: Trunk (master)

**Additional Context**
The use case that I actually had here in #2519 was that of a cell of text that might contain multiple URLs would be convenient to be able to click on the URLs and it open a browser for quick verification during reconciling processes.

As long as scrolling the grid still works, editing the cells still works, running GREL operations on the cell text, and exporting the cells still works, then I think it satisfies most of the needs that will come up within GLAM reconciling processes with multiple URLs in a cell text for clicking and verifying.

### PR DESCRIPTION
**Pull request by singhakshita**
fixes #2519  
due to some conflict issues and due to shown changes in huge number of files (which i never did) i have to send another pull request

### CODE REVIEW

**Comment by fgiroud** [comment]
Is this ready for review ?
Your code should be linted, and the file should probably go under `grid/misc/cell_display.spec.js`, as this is not a transform I think

**Comment by singhakshita** [comment]
yes this is up for review

**Review by fgiroud — APPROVED** [review]

**Comment by fgiroud** [comment]
Good on the testing side, @thadguidry do you mind to review the changes ?

**Comment by thadguidry** [comment]
@fgiroud I'd rather not.

File: main/tests/cypress/cypress/integration/project/grid/misc/proper-display.js [hunk 1]
```diff
@@ -0,0 +1,23 @@
+describe(__filename, function () {
+  it('proper tag assingnment to each text snippet', function () {
```
Comment (kushthedude) [inline main/tests/cypress/cypress/integration/project/grid/misc/proper-display.js:2]: typo

File: main/tests/cypress/cypress/integration/project/grid/misc/proper-display.js [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+    const fixture = [
+      ['tests'],
+      ['2021-01-31https://www.google.com'],
+      [
+        'https://www.wikidata.org/wiki/Property:P670 https://www.wikidata.org/wiki/Property:P669 are now mapped to https://schema.org/streetAddress via https://www.wikidata.org/wiki/Property:P2235',
+      ],
+      ['vhjhjjj https://github.com/OpenRefine/OpenRefine/issues/2519'],
```
Comment (kushthedude) [inline main/tests/cypress/cypress/integration/project/grid/misc/proper-display.js:9]: Can you please change this column name to something more appropriate?

File: main/webapp/modules/core/scripts/views/data-table/cell-ui.js [hunk 3]
```diff
@@ -96,17 +96,35 @@ DataTableCellUI.prototype._render = function() {
...
-      url.textContent = cell.v;
-      url.setAttribute('href', cell.v);
-      url.setAttribute('target', '_blank');
-      divContent.appendChild(url);
     } else {
-      var span = document.createElement('span');
-      span.textContent = cell.v;
-      divContent.appendChild(span);
-    }
+      var arr = cell.v.split(" ");
```
Comment (kushthedude) [inline main/webapp/modules/core/scripts/views/data-table/cell-ui.js:100]: > The cell's value should be shown as text and not as a valid hyperlink.
(I think what is happening is that our current code just looks for a string beginning with http:// or https:// and doesn't care about validation or remaining characters such as whitespace after that, but should)
I think this is mentioned elsewhere in another related issue but couldn't find it.
Browsers now have native support for URL detection and we should take advantage of that.

Can you please see the desired behaviours, if I have the text as **https://www.wikidata.org/wiki/Property:P670 https://www.wikidata.org/wiki/Property:P669 are now mapped to https://schema.org/streetAddress via https://www.wikidata.org/wiki/Property:P2235** it should be displayed as a `span`, not a `hyperlink`? What the logic does over here is first splits the complete text by space and then checks the each as URL function and then appends them to a new array and other non-matching elements to another array bucket which in itself is quite complex logic. Also, the current logic can also be improved further rather than having a for loop to iterate over an array, the changes should be done in looksLikeURL function to not do the judgement on the basis of protocol prefix.
I would still rely on @wetneb and @thadguidry feedback on this behaviour.

File: main/tests/cypress/cypress/integration/project/grid/misc/proper-display.js [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+    ];
+    cy.loadAndVisitProject(fixture);
+
+    cy.getCell(0, 'tests').contains('2021-01-31https://www.google.com');
+    cy.getCell(1, 'tests')
```
Comment (kushthedude) [inline main/tests/cypress/cypress/integration/project/grid/misc/proper-display.js:14]: Can this test also check if there is `span` too as this is only checking the presence of `href`?

**Review by kushthedude — CHANGES_REQUESTED** [review]

File: main/webapp/modules/core/scripts/views/data-table/cell-ui.js (hunk 3 above)
Comment (tfmorris) [reply main/webapp/modules/core/scripts/views/data-table/cell-ui.js:100]: The behavior should match the ticket, but I think the current implementation is better than what's proposed on the ticket, so I'd suggest that we update the ticket instead of the code. I think the main thrust of the bug report is that multiple URLs or a URL followed by extra text shouldn't be hyperlinked as a single HREF, which this satisfies.

File: main/webapp/modules/core/scripts/views/data-table/cell-ui.js [hunk 5]
```diff
@@ -96,17 +96,35 @@ DataTableCellUI.prototype._render = function() {
...
+            url.setAttribute('target', '_blank');
+            divContent.appendChild(url);
+            if (i == arr.length-1) {
+             divContent.appendChild(url)
+            } else {
+            divContent.appendChild(url).appendChild(document.createTextNode('\u00A0'));
+            }
+          } else {
+          spanArr.push(arr[i]);
+          }
```
Comment (tfmorris) [inline main/webapp/modules/core/scripts/views/data-table/cell-ui.js:121]: Indentation needs cleanup - 2 space indents should be used for each level. Any good IDE should be able to do this for you automatically.

**Review by tfmorris — CHANGES_REQUESTED** [review]
Thanks for including the test. Things are getting closer, but still a couple of things to clean up. I would hold off on changing things functionally until we have consensus on the desired behavior, but please go ahead and clean up the other stuff that @kushthedude and I mentioned. 

Also, please edit the your original description to include the phrase "Fixes #2519" so that Github links the PR with the issue that it fixes (and will automatically close the issue when we merge the PR).

For reference, this is a follow-on #3591, which I reviewed before, and #3588, which got reverted.

File: main/webapp/modules/core/scripts/views/data-table/cell-ui.js (hunk 3 above)
Comment (singhakshita) [reply main/webapp/modules/core/scripts/views/data-table/cell-ui.js:100]: "  https://www.wikidata.org/wiki/Property:P670 https://www.wikidata.org/wiki/Property:P669 are now mapped to https://schema.org/streetAddress via https://www.wikidata.org/wiki/Property:P2235 " 
i think the desired behaviour is ,it should be able to uniquely identify each text component and each url ,and it does so .
Screenshot 2021-02-10 at 7 40 42 AM

also i think if the text contain both url and normal tag , should it entirely be in <a> or <span> tag ,i guess  each component of it should be assigned a tag depending upon what it is ,whether a text or an url .

if i am getting anything wrong please let me know . @kushthedude 
Screenshot 2021-02-10 at 7 48 56 AM

it may seem like its adding extra spaces or manipulating the data but please look to this

File: main/tests/cypress/cypress/integration/project/grid/misc/proper-display.js (hunk 1 above)
Comment (singhakshita) [reply main/tests/cypress/cypress/integration/project/grid/misc/proper-display.js:2]: okay

File: main/tests/cypress/cypress/integration/project/grid/misc/proper-display.js (hunk 2 above)
Comment (singhakshita) [reply main/tests/cypress/cypress/integration/project/grid/misc/proper-display.js:9]: yes

File: main/tests/cypress/cypress/integration/project/grid/misc/proper-display.js (hunk 4 above)
Comment (singhakshita) [reply main/tests/cypress/cypress/integration/project/grid/misc/proper-display.js:14]: yes

File: main/webapp/modules/core/scripts/views/data-table/cell-ui.js (hunk 5 above)
Comment (singhakshita) [reply main/webapp/modules/core/scripts/views/data-table/cell-ui.js:121]: yes working on it

Comment (thadguidry) [reply main/webapp/modules/core/scripts/views/data-table/cell-ui.js:121]: @tfmorris @kushthedude @singhakshita - I have updated https://github.com/OpenRefine/OpenRefine/issues/2519#issue-595223760 to give some Additional Context into the use case.  Please take a look.

Comment (singhakshita) [reply main/webapp/modules/core/scripts/views/data-table/cell-ui.js]: i have updated span test , typos fixed ,indentation fixed.  i guess we now can recognise all separate urls as mentioned by @thadguidry  , if any thing else is supposed to be done please let me know

**Comment by wetneb** [comment]
@singhakshita you have included "fixes #2519" in the title of your pull request, but it should not be there. It should be in the description (the first comment in the discussion), in other words the body text (the one you type in a `<textarea>`, where you wrote `issue #2519`).

**Comment by singhakshita** [comment]
@wetneb  sorry and thanks for your patience

**Comment by wetneb** [comment]
No worries, this GitHub feature is not very well discoverable and confuses most of our new contributors at the moment.

**Review by tfmorris — APPROVED** [review]
LGTM. Thanks for the contribution!
