### PR TITLE
Fixes a NPE exception in edit generation in the Wikibase extension

### LINKED ISSUE #2880: NPE in edit generation in the Wikidata extension
**Describe the bug**
Generating edits for string values can fail in the presence of null cells.

**To Reproduce**
1. Create a schema that adds a label from a row with a null cell
2. Observe the error

(I cannot believe I have not run into this bug earlier!)

**Current Results**
```
java.lang.NullPointerException
	at org.openrefine.wikidata.schema.WbStringVariable.fromCell(WbStringVariable.java:59)
	at org.openrefine.wikidata.schema.WbStringVariable.fromCell(WbStringVariable.java:39)
	at org.openrefine.wikidata.schema.WbVariableExpr.evaluate(WbVariableExpr.java:82)
	at org.openrefine.wikidata.schema.WbStatementExpr.evaluate(WbStatementExpr.java:95)
	at org.openrefine.wikidata.schema.WbStatementGroupExpr.evaluate(WbStatementGroupExpr.java:63)
	at org.openrefine.wikidata.schema.WbItemDocumentExpr.evaluate(WbItemDocumentExpr.java:79)
	at org.openrefine.wikidata.schema.WikibaseSchema.evaluateItemDocuments(WikibaseSchema.java:114)
	at org.openrefine.wikidata.schema.WikibaseSchema$EvaluatingRowVisitor.visit(WikibaseSchema.java:171)
	at com.google.refine.browsing.util.RowVisitorAsRecordVisitor.visit(RowVisitorAsRecordVisitor.java:61)
	at com.google.refine.browsing.util.ConjunctiveFilteredRecords.accept(ConjunctiveFilteredRecords.java:64)
	at com.google.refine.browsing.util.FilteredRecordsAsFilteredRows.accept(FilteredRecordsAsFilteredRows.java:50)
	at org.openrefine.wikidata.schema.WikibaseSchema.evaluate(WikibaseSchema.java:142)
	at org.openrefine.wikidata.commands.PreviewWikibaseSchemaCommand.doPost(PreviewWikibaseSchemaCommand.java:88)
```

**Expected behavior**
The value should be skipped.

**OpenRefine :**
 - Version 3.4 beta2

### PR DESCRIPTION
**Pull request by wetneb**
Fixes #2880.

Changes proposed in this pull request:
- Make schema evaluation null-proof;
- Avoid adding null values in data extension operation

### CODE REVIEW

File: main/tests/server/src/com/google/refine/operations/recon/ExtendDataOperationTests.java [hunk 1]
```diff
@@ -249,7 +249,7 @@ public void testFetchStrings() throws Exception {
       		  "{"
   			+ "\"rows\": {"
   			+ "    \"Q794\": {\"P297\": [{\"str\": \"IR\"}]},"
-  			+ "    \"Q863\": {\"P297\": [{\"str\": \"TJ\"}]},"
+  			+ "    \"Q863\": {\"P297\": []},"
```
Comment (wetneb) [inline main/tests/server/src/com/google/refine/operations/recon/ExtendDataOperationTests.java:252]: This test was changed to make sure the data extension operation does not create non-null cells with null values.

**Comment by wetneb** [comment]
If you feel like reviewing this, @afkbrb, it would be quite useful too (no worries if you don't have time).

**Comment by wetneb** [comment]
Merging this in the coming days unless anyone has concerns.
