### PR TITLE
Fix a bug of object array convertion and adjust error message

### LINKED ISSUE #5463: replaceEach function not working and mis-documented
At https://docs.openrefine.org/manual/grelfunctions#replaceeach-s-a-find-a-replace in the GREL manual, the documentation describes a function replaceEach with syntax

replaceEach(s, a find, a replace)

But the example in the subsequent description uses a function called replaceEachFromArrays, and if you try this example you do indeed get an Unknown function error. However, using replaceEach with the syntax described also always produces an error

_Error: replaceEach expects 3 arguments: string, array of strings to replace, array of replacement strings_

even when using the correct argument types. Try, for instance,

`"The cow jumps over the moon and moos".replaceEach(["th", "moo"], ["ex", "mee"])`

I am using OpenRefine Version 3.6.2 [579a6f7] in Safari Version 16.1 on MacOS 12.6.1 .

### PR DESCRIPTION
**Pull request by Huishin-pie**
Fixes #5463 

Changes proposed in this pull request:
- Fix a bug of object array convertion
- Adjust error message

### CODE REVIEW

File: main/src/com/google/refine/expr/functions/strings/ReplaceEach.java [hunk 1]
```diff
@@ -45,7 +55,7 @@ public Object call(Properties bindings, Object[] args) {
                     }
 
                     // replace each occurrence of search with corresponding element in replace
-                    return StringUtils.replaceEachRepeatedly(str, search, replace);
+                    return StringUtils.replaceEachRepeatedly((String) args[0], search, replace);
```
Comment (tfmorris) [inline main/src/com/google/refine/expr/functions/strings/ReplaceEach.java:58]: This is going to collide with `com.google.refine.util.StringUtils`, so let's switch to the fully qualified name here, since it's the only occurrence.
```suggestion
                    return org.apache.commons.lang.StringUtils.replaceEachRepeatedly((String) args[0], search, replace);
```

File: main/src/com/google/refine/expr/functions/strings/ReplaceEach.java [hunk 2]
```diff
@@ -25,13 +25,23 @@ public class ReplaceEach implements Function {
...
+                String[] search = searchArgs, replace;
+
                 if (args[2] instanceof String) {
                     replace = new String[] { (String) args[2] };
                 } else {
-                    replace = (String[]) args[2];
+                    String[] replaceArgs = new String[((Object[]) args[2]).length];
+                    Object[] originalReplaceArgs = (Object[]) args[2];
+                    for (var i = 0; i < replaceArgs.length; i++) {
+                        replaceArgs[i] = originalReplaceArgs[i].toString();
```
Comment (tfmorris) [inline main/src/com/google/refine/expr/functions/strings/ReplaceEach.java:42]: For consistency in string conversion, please use our utility method from `com.google.refine.util.StringUtils` to handle this (you'll need to adjust the imports):
```suggestion
                        replaceArgs[i] = StringUtils.toString(originalReplaceArgs[i]);
```

**Review by tfmorris — CHANGES_REQUESTED** [review]
Looks really good. We have a utility method for `toString()` conversions, so let's use that for consistency.

Also, please add test coverage for some additional code paths:
- replacement array shorter than search array (to test array extension/fill)
- non-string (e.g. int, float, null) search/replace values (to test the toString() conversion)

Other than that it looks ready to go

**Review by tfmorris — APPROVED** [review]
Looks great. Thank you!
