### PR TITLE
Fix regex filter error

### LINKED ISSUE #1203: Filter by regex - grey window spinning wheel on version 2.7
Hi,
I'm using the 2.7 version, with linux (Ubuntu 17.04), Firefox.
My dataset contains +/- 1200 rows and 20 columns.

If I ask a column to be filtered by a regex, and once refine starts to interpret the regex, The page turns grey and I cannot interact with my dataset without having to reload the page.  

Can you repeat this bug on your machines? Or is it just me?

### PR DESCRIPTION
**Pull request by ostephens**
To fix #1203 
- Changes get-rows call to request JSON rather than JSONP
- Catches situations where JSON returned for get-rows or compute-facets includes an 'error' element
  - Where there is an error with get-rows, the existing row set is used for the data-table
  - Where there is an error with compute-facets, the error message from the JSON is displayed at the top of the facets/filter sidebar (some minor modifications to css and DOM manipulation were needed to achieve this alongside the 'refreshing facets' notification)

Comments welcome

### CODE REVIEW

File: main/webapp/modules/core/scripts/project/browsing-engine.js [hunk 1]
```diff
@@ -240,19 +241,31 @@ BrowsingEngine.prototype.update = function(onDone) {
...
+        var clearErr = $('#err-text').remove();
+        var err = $('<div id="err-text">')
+                  .text(data.message)
+                  .appendTo(self._elmts.errors);
+         self._elmts.errors.css("display", "block");
+        if (onDone) {
+          onDone();
+        }
+        return;
+      }
```
Comment (wetneb) [inline main/webapp/modules/core/scripts/project/browsing-engine.js]: In principle I'd prefer an `if () { ... } else { ... }` rather than `if () { ... ; return; } ...` but it's clearly not a big deal…

**Comment by thadguidry** [comment]
@ostephens same look and feel in Firefox and Chrome ?

**Comment by thadguidry** [comment]
@ostephens Just a minor training point.  In Java and Javascript, there are standard equality operands and STRICT equality operands.  One does the type conversion AND THEN does the equality check, and the other does not do type conversion, I.E. it is STRICT.  If your comparing identity, you want to ensure your using STRICT operands (also known as the identity compare operands) (===, !==) Always use the bible reference with a handy chart at the bottom https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators

In Java, its common practice for String comparisons to use .equals() rather than === , but its a preference and the later only available in later JDK's.

Your doing GREAT however, Owen, and really like these constant commits from you !  Keep up the learning !

**Comment by jackyq2015** [comment]
looks good for me. will merge.

**Comment by ostephens** [comment]
Thanks all. @thadguidry yes have checked it in Safari, FF & Chrome. 

Thanks to you all for guidance & encouragement :)
