### PR TITLE
Standardise 'edit' cell dialogue with 'toNumber()' when parsing String to Number

### LINKED ISSUE #2163: When using the cell "Edit" option to enter a number, the behaviour should be consistent with toNumber()
**Describe the bug**
If you enter a string into a cell such as "3" and then use "toNumber()" to convert it to a number, toNumber() first tries to parse as a Long, and then tries parsing as a Double. So "3" will be stored as a Long, while "3.0" will be stored as a Double

However, if you edit a cell by using the single cell "edit" option and enter a number, and change the 'type' to Number, OR only attempts to parse the string typed into the cell edit dialogue as a Double - meaning that "3" is stored as a Double, not a Long. This means that entering "3" and "3.0" have exactly the same result in this case.

**Expected behavior**
The two options should be consistent in terms of how they parse strings to numbers and store the data.

The 'toNumber()' behaviour is preferred, and the 'edit' cell dialogue should be consistent with 'toNumber()' when entering numbers into cells

**OpenRefine (please complete the following information):**
 - Version 3.2

**Additional context**
https://groups.google.com/d/msg/openrefine/8uq_mZMISCs/E4IKWNHeBQAJ

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #2163 

```
The implementation for two ways of parsing String to Number 
in cells is inconsistent:

1. 'Edit' cell dialogue and switch type to 'number':
Tries to parse String as a Double.

2. Using 'toNumber()' in cell transformations:
Tries to parse String as a Long, then parse String as a Double.

This PR modifies the 'edit' cell dialogue implementation 
to standardise with the latter, with the aim of eliminating 
inconsistent handling.
```

### CODE REVIEW

**Comment by jamessspanggg** [comment]
hi @thadguidry, may I ask if the implementation for this PR alright before I open this for reviews?

**Comment by thadguidry** [comment]
Hi @jamessspanggg thanks for drafting this PR !  We'll let @wetneb (our lead developer) review this and he'll respond to you here.

**Comment by thadguidry** [comment]
- By the way, are you still going to school at http://www.comp.nus.edu.sg/  ?
- What are your study / interest areas?

We would love to have you work on even more areas of OpenRefine!
I reviewed some of your previous commits across Github activity and your awesome!
 - Are you interested as a GSOC Summer Intern 2020 for us by chance?

**Comment by jamessspanggg** [comment]
Hi @thadguidry, thanks for the offer!

> * By the way, are you still going to school at http://www.comp.nus.edu.sg/  ?

Yes I am still a student in National University of Singapore.

> * What are your study / interest areas?

I am a third year Computer Science undergraduate, with Software Engineering and Artificial Intelligence as my focus area.

> * Are you interested as a GSOC Summer Intern 2020 for us by chance?

Yes I am interested! How so I go about applying for this? (when should I apply etc)

**Comment by wetneb** [comment]
Hi @jamessspanggg, thanks a lot for both pull requests!
By marking them as drafts, is your intention to signal that you still want to work on these before we review them? Feel free to mark them as ready for review directly if you want feedback about them. "Review" might sound a bit intimidating but it should not: if there are any issues that is totally fine, you can fix them later on :)

**Comment by jamessspanggg** [comment]
Hi @wetneb, my bad, this PR is ready for review.

**Comment by wetneb** [comment]
Thanks! It looks great to me. Would you consider writing a test to demonstrate the change? I imagine we could have a simple test which creates a project, applies this command on a cell, and checks that the cell value has the appropriate type afterwards, for instance.

Our test coverage is pretty bad so we encourage contributors to write tests for the features they introduce / bugs they fix so that we gradually build a better test suite :) If you are not familiar with this sort of testing, let me know if I can help.

Conserning the Google Summer of Code, all the infos are here: https://summerofcode.withgoogle.com/
We are in the process of applying as a project. The application period for students is later.
We have started writing down a few ideas for GSoC projects: https://github.com/OpenRefine/OpenRefine/wiki/GSoC-2020%C2%A0Ideas

**Comment by jamessspanggg** [comment]
> Thanks! It looks great to me. Would you consider writing a test to demonstrate the change? 

Noted. Will do so when I'm more familiar with the codebase.
 
> Conserning the Google Summer of Code, all the infos are here: https://summerofcode.withgoogle.com/
> We are in the process of applying as a project. The application period for students is later.

Thanks for the info, will keep an eye for that!

**Comment by wetneb** [comment]
> Noted. Will do so when I'm more familiar with the codebase.
OK! So let's keep this PR open until then.

**Comment by jamessspanggg** [comment]
@wetneb I have added the necessary test cases. Let me know if they need changes.

Also, I noted that the front-end testing framework used is WindMill, which is no longer being maintained. Since the current front-end testing code is rather small, should we migrate to a more recent framework e.g. Cypress?

File: main/tests/server/src/com/google/refine/commands/cell/EditOneCellCommandTests.java [hunk 1]
```diff
@@ -62,6 +65,42 @@ public void testEditOneCell() throws ServletException, IOException {
...
+		when(request.getParameter("project")).thenReturn(Long.toString(project.id));
+		when(request.getParameter("row")).thenReturn("1");
+		when(request.getParameter("cell")).thenReturn("0");
+		when(request.getParameter("type")).thenReturn("number");
+		when(request.getParameter("value")).thenReturn(PARSABLE_LONG_NUMBER);
+		when(request.getParameter("csrf_token")).thenReturn(Command.csrfFactory.getFreshToken());
+
+		command.doPost(request, response);
+
+		assertEquals("a", project.rows.get(0).cells.get(0).value);
```
Comment (jamessspanggg) [inline main/tests/server/src/com/google/refine/commands/cell/EditOneCellCommandTests.java]: wonder if I should still check for the other cells.
