### PR TITLE
Fix wikibase date export format

### LINKED ISSUE #3694: timestamp for Wikidata export: +2021-00-00 versus +2021-01-01
When exporting dates with a precision smaller than days, OpenRefine (Version 3.4.1) seems to export the year 1883 (as a random example) as +1883-01-01T00:00:00Z both with the export tool and QuickStatements.

However, if I understand those links correctly, it should be +1883-00-00T00:00:00Z (even though this isn’t ISO style):

https://www.wikidata.org/wiki/Help:Dates#Time_datatype
https://www.wikidata.org/wiki/Wikidata:Project_chat/Archive/2021/02#Dates_with_%3C11_precision
https://www.mediawiki.org/wiki/Wikibase/DataModel#Dates_and_times

While an argument could be made that Wikibase should normalize those entries, this isn’t the case at the moment, so I wondered if you could adjust OpenRefine’s behaviour. Thank you!

### PR DESCRIPTION
**Pull request by loulankxh**
Fixes #3694

Changes proposed in this pull request:
- Adjust "extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateConstant.java" and add a variable "segment" to judge whether the date has a precision smaller than year, month or day
- Adjust "extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbDateConstantTest.java" accordingly to test correctness.
- Note that the basic classes such as "Date" and "Calendar" are not modified since the authority is not assigned and I also think there isn't necessity to modify them because time like "1883-00-00T00:00:00Z" is actually not a real valid date.

### CODE REVIEW

**Comment by loulankxh** [comment]
Totally 5 test files in module wikidata are changed to adapt to the modification according to date precision

File: extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateConstant.java [hunk 1]
```diff
@@ -123,7 +123,9 @@ public static TimeValue parse(String datestamp)
             trimmedDatestamp = trimmedDatestamp.substring(1);
             bceFlag = true;
         }
-    	
+
+        int segment = trimmedDatestamp.split("-").length;  // judge whether the precision is smaller than year, month or day
```
Comment (wetneb) [inline extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateConstant.java:127]: I don't think we need to introduce this variable, we should be able to rely on the `precision` variable further down. That should be more reliable (because we could potentially introduce new date formats with more dashes in them).

File: extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateConstant.java [hunk 2]
```diff
@@ -161,10 +163,12 @@ public static TimeValue parse(String datestamp)
             calendar = Calendar.getInstance();
             calendar.setTime(bestDate);
             long year = calendar.get(Calendar.YEAR);
+            int month = segment > 1 ? calendar.get(Calendar.MONTH) + 1: 0;
```
Comment (wetneb) [inline extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateConstant.java:166]:
```suggestion
            int month = precision < 10 ? calendar.get(Calendar.MONTH) + 1: 0;
```

File: extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateConstant.java [hunk 3]
```diff
@@ -161,10 +163,12 @@ public static TimeValue parse(String datestamp)
...
+            int day_of_month = segment > 2 ? calendar.get(Calendar.DAY_OF_MONTH) : 0;
```
Comment (wetneb) [inline extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateConstant.java:167]:
```suggestion
            int day_of_month = precision < 11 ? calendar.get(Calendar.DAY_OF_MONTH) : 0;
```

File: extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WikibaseSchemaTest.java [hunk 4]
```diff
@@ -158,6 +158,7 @@ public void testEvaluateRespectsFacets()
         List<ItemUpdate> expected = new ArrayList<>();
         ItemUpdate update1 = new ItemUpdateBuilder(qid1).addStatement(statement1).build();
         expected.add(update1);
+        System.out.println(expected);
```
Comment (wetneb) [inline extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WikibaseSchemaTest.java:161]: We can probably remove this `System.out.println` call.

**Review by wetneb — COMMENTED** [review]
Thank you very much! It looks great to me. I just have a couple of minor comments below.

File: extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WikibaseSchemaTest.java (hunk 4 above)
Comment (loulankxh) [reply extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WikibaseSchemaTest.java:161]: Sorry， I forget to delete this

**Review by wetneb — APPROVED** [review]
Thank you very much!

**Comment by loulankxh** [comment]
Thanks really!
