### PR TITLE
fixes #6330 Trim whitespace when converting stream to string in Impor…

### LINKED ISSUE #6330: Creating a project from a URL with a trailing space fails
### To Reproduce
1. First, launch OpenRefine and go to "Create Project" -> "Web Adresses (URL)"
2. Then, type in a URL with a trailing space at the end, such as "https://datasets.imdbws.com/name.basics.tsv.gz "
3. Finally, press "Next »"

### Current Results

Error: 
```
Error uploading data
Illegal character in path at index 46: https://datasets.imdbws.com/name.basics.tsv.gz "
```

### Expected Behavior

The whitespace is trimmed and the project is successfully created.

### Versions
 - OpenRefine: master branch

### PR DESCRIPTION
**Pull request by surajbora59**
…tingUtilities.java

Fixes #6330

Changes proposed in this pull request:
Remove trailing space for url before assign to urlString

### CODE REVIEW

**Review by wetneb — CHANGES_REQUESTED** [review]
Thank you! That looks like a valid fix.

Do you think you could write an accompanying test for it? You should be able to take inspiration from existing tests in `ImportingUtilitiesTests.java`.

**Comment by surajbora59** [comment]
@wetneb Have added the test case for this also, please have a look if test case looks fine.

**Comment by wetneb** [comment]
@surajbora59 nice! It looks like the CI is failing because of some style changes. You could fix that by running `./refine lint` and committing the results.

**Comment by surajbora59** [comment]
@wetneb pushed the changes from by running `./refine lint` command.

File: main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java [hunk 1]
```diff
@@ -497,4 +499,61 @@ public void testIsCompressedFile() throws IOException {
...
+                                JSONUtilities.safePut(progress, "message", message);
+                            }
+                            JSONUtilities.safePut(progress, "percent", percent);
+                        }
+
+                        @Override
+                        public boolean isCanceled() {
+                            return job.canceled;
+                        }
+                    });
```
Comment (wetneb) [inline main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java:553]: Maybe we could do with an `Assert.fail()` here to make sure an exception was indeed thrown, otherwise the assertion in the catch block will be silently ignored (similarly to the test case you copied this from).

Alternatively you could start from the test case for a successful import, it would perhaps be a bit more natural.

Comment (surajbora59) [reply main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java]: I have added the assert in try block, also from one of test case I have tried to start test case for successful import not sure if it is correct.

Comment (surajbora59) [reply main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java]: Also for successful import I would be needing a file hosted somewhere that will be the issue here for this test case.

**Comment by wetneb** [comment]
My bad, I thought we had a test case for a successful URL import, but it does look like we haven't got that yet (we could add one without relying on an online location, we could use HTTP mocking like in the test case you wrote). That's fine, the way you do it is a valid way to test your fix.

We probably only need to `./refine lint` again and it should be good to go. Thanks for your perseverance!

**Comment by surajbora59** [comment]
image


No changes at my end after formatting the code.

I noticed that above workflow failed due to not able to resolve some dependencies
PFB, screenshot for that workflow


image

**Comment by surajbora59** [comment]
Re-running the workflow is likely to resolve the problem.

**Review by wetneb — APPROVED** [review]
Thank you very much!
