### PR TITLE
Fixes #4485 DB Extension autoclose stream with try with resources

### LINKED ISSUE #4485: stream not closed if dbextension.properties is customized and secured via another user acccount
If `dbextension.properties` is customized and given alternate permissions, than while attempting a stream of file, an exception is logged but the stream isn't effectively closed.

### To Reproduce
1. Change permissions on dbextension.properties 

### Current Results
stream is left open

### Expected Behavior
stream should be autoclosed with newer try with resources

### Versions
 - Operating System: Windows 11 (WSL2 virtual environment for test user account)
 - Browser Version: Firefox
 - JRE or JDK Version: JDK 17.0.1
 - OpenRefine: master branch

### PR DESCRIPTION
**Pull request by thadguidry**
Fixes #4485

Changes proposed in this pull request:
- Updates DB Extension to use newer try with resources to autoclose properties stream regardless

### CODE REVIEW

File: extensions/database/src/com/google/refine/extension/database/DatabaseModuleImpl.java [hunk 1]
```diff
@@ -111,20 +111,18 @@ private Properties loadProperties(File propFile) {
                 if(logger.isDebugEnabled()) {
                     logger.debug("Loading Extension properties ({})", propFile);
                 }
-                BufferedInputStream stream = null;
-                try {
-                     ps = new Properties();
-                    stream = new BufferedInputStream(new FileInputStream(propFile));
+                final BufferedInputStream stream = new BufferedInputStream(new FileInputStream(propFile));
+                try (stream) {
```
Comment (wetneb) [inline extensions/database/src/com/google/refine/extension/database/DatabaseModuleImpl.java:115]: Why not put the whole variable assignment into the `try ( )`? Like the first example here: https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

Comment (thadguidry) [reply extensions/database/src/com/google/refine/extension/database/DatabaseModuleImpl.java]: it felt "longish", but that's fine.

**Review by wetneb — APPROVED** [review]
