### PR TITLE
Handle NumberFormatException thrown in DatabaseImportController

### LINKED ISSUE #2509: OpenRefine 3.3 throws Number Format Exception on Windows 10 when trying to preview query
When I connect to my MySQL DB, I'm asked to enter a query and when I keep a simple query "SELECT * FROM mytable", It displays "Updating Preview" Forever and throws an exception in Command Line. Sharing the logs:

Logs:07:49:14.972 [                   refine] GET /command/core/get-csrf-token (253429ms)
07:49:14.979 [                   refine] POST /command/core/cancel-importing-job (7ms)
07:49:19.654 [                   refine] GET /command/database/saved-connection (4675ms)
07:49:19.664 [                   refine] GET /command/core/get-csrf-token (10ms)
07:49:19.673 [                   refine] POST /command/database/connect (9ms)
07:49:25.019 [                   refine] GET /command/core/get-csrf-token (5346ms)
07:49:25.025 [                   refine] POST /command/database/test-query (6ms)
07:49:25.047 [                   refine] GET /command/core/get-csrf-token (22ms)
07:49:25.052 [                   refine] POST /command/core/create-importing-job (5ms)
07:49:25.104 [                   refine] GET /command/core/get-csrf-token (52ms)
07:49:25.111 [                   refine] POST /command/core/importing-controller (7ms)
07:49:25.130 [                   refine] GET /command/core/get-csrf-token (19ms)
07:49:25.137 [                   refine] POST /command/core/importing-controller (7ms)
07:49:25.137 [          org.mortbay.log] /command/core/importing-controller (0ms)
java.lang.NumberFormatException: null
        at java.base/java.lang.Integer.parseInt(Integer.java:614)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at com.google.refine.extension.database.DatabaseImportController.getQueryInfo(DatabaseImportController.java:453)
        at com.google.refine.extension.database.DatabaseImportController.doParsePreview(DatabaseImportController.java:184)
        at com.google.refine.extension.database.DatabaseImportController.doPost(DatabaseImportController.java:100)
        at com.google.refine.commands.importing.ImportingControllerCommand.doPost(ImportingControllerCommand.java:68)
        at com.google.refine.RefineServlet.service(RefineServlet.java:189)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

Desktop:
Windows 10 
Chrome Latest
Java version "11.0.5" 2019-10-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.5+10-LTS, mixed mode)

**OpenRefine (please complete the following information):**
OpenRefine 3.3

### PR DESCRIPTION
**Pull request by Gomaa**
fixes #2509  The number format exception will be caught in case of any invalid port numbers.

### CODE REVIEW

File: extensions/database/src/com/google/refine/extension/database/DatabaseImportController.java [hunk 1]
```diff
@@ -450,7 +450,11 @@ private DatabaseQueryInfo getQueryInfo(HttpServletRequest request) {
         jdbcConfig.setConnectionName(request.getParameter("connectionName"));
         jdbcConfig.setDatabaseType(request.getParameter("databaseType"));
         jdbcConfig.setDatabaseHost(request.getParameter("databaseServer"));
-        jdbcConfig.setDatabasePort(Integer.parseInt(request.getParameter("databasePort")));
+        try {
+        	jdbcConfig.setDatabasePort(Integer.parseInt(request.getParameter("databasePort")));
+        }catch(NumberFormatException nfE) {
```
Comment (wetneb) [inline extensions/database/src/com/google/refine/extension/database/DatabaseImportController.java:455]:
```suggestion
        } catch(NumberFormatException nfE) {
```

File: extensions/database/src/com/google/refine/extension/database/DatabaseImportController.java [hunk 2]
```diff
@@ -450,7 +450,11 @@ private DatabaseQueryInfo getQueryInfo(HttpServletRequest request) {
...
+        	logger.error("getQueryInfo :: NumberFormatException ::{}", nfE);
```
Comment (wetneb) [inline extensions/database/src/com/google/refine/extension/database/DatabaseImportController.java:456]:
```suggestion
        	logger.error("getQueryInfo :: invalid database port ::{}", nfE);
```

File: extensions/database/src/com/google/refine/extension/database/DatabaseImportController.java (hunk 1 above)
Comment (tfmorris) [reply extensions/database/src/com/google/refine/extension/database/DatabaseImportController.java:455]: Why was this marked as resolved when the change suggested by @wetneb (space between the brace and `catch`) wasn't made?
```suggestion
        } catch(NumberFormatException nfE) {
```
