### PR TITLE
Fix DeleteProject NPE during e2e tests. Fixes #3479.

### LINKED ISSUE #3479: Not all test projects created during ui_testing are getting scraped
We already have an afterEach hook that deletes all the projects created during the test but due to some bug, not all projects are being deleted.
### To Reproduce
1. Open Cypress application
2. Run a Spec
3. See a few outstanding projects remaining

### Current Results

Few projects remains after successful afterEach hook.
### Expected Behavior

All projects should be flushed out

### PR DESCRIPTION
**Pull request by tfmorris**
Fixes #3479 

- refactor & DRY up tag management code
- add some tests for project related commands
- add tests for tag commands

### CODE REVIEW

File: main/tests/server/src/com/google/refine/commands/CommandTestBase.java [hunk 1]
```diff
@@ -40,4 +43,13 @@ public void setUpRequestResponse() {
     protected void assertCSRFCheckFailed() {
         TestUtils.assertEqualsAsJson(writer.toString(), "{\"code\":\"error\",\"message\":\"Missing or invalid csrf_token parameter\"}");
     }
+
+    /**
+     * Convenience method to check that CSRF protection was NOT triggered
+     */
+    protected void assertErrorNotCSRF() {
+        String response = writer.toString();
+        assertTrue(response.contains("\"code\":\"error\""));
```
Comment (wetneb) [inline main/tests/server/src/com/google/refine/commands/CommandTestBase.java:52]: This relies on the response containing JSON formatted in a specific way (without spaces around `:`), which I'd rather avoid. What motivates you not to use the helper above?

Comment (tfmorris) [reply main/tests/server/src/com/google/refine/commands/CommandTestBase.java:52]: If "helper above" means `assertCSRFCheckFailed()`, it's testing for a different case. This helper is checking for `code: "error"` and `message: <anything but invalid csrf_token>`.

I can invest additional effort in coding it to protect against a potential future JSON formatting change if you think it's important.

Comment (wetneb) [reply main/tests/server/src/com/google/refine/commands/CommandTestBase.java:52]: Ah right, I missed the negation. Yes I think it would be cleaner to parse the JSON and then access the fields of the resulting `JsonNode`.

File: main/tests/server/src/com/google/refine/commands/CommandTestBase.java [hunk 2]
```diff
@@ -47,9 +50,11 @@ protected void assertCSRFCheckFailed() {
     /**
      * Convenience method to check that CSRF protection was NOT triggered
      */
-    protected void assertErrorNotCSRF() {
+    protected void assertErrorNotCSRF() throws JsonProcessingException {
         String response = writer.toString();
-        assertTrue(response.contains("\"code\":\"error\""));
+        ObjectMapper mapper = new ObjectMapper();
+        JsonNode node = mapper.readValue(response, JsonNode.class);
```
Comment (wetneb) [inline main/tests/server/src/com/google/refine/commands/CommandTestBase.java:56]: Thank you! `ObjectMapper` objects are sort of expensive to instantiate so Jackson recommends to reuse a centrally-initialized instance. You could just do that by using `ParsingUtilities.mapper`.

File: main/tests/server/src/com/google/refine/commands/CommandTestBase.java (hunk 1 above)
Comment (tfmorris) [reply main/tests/server/src/com/google/refine/commands/CommandTestBase.java]: I've updated the test. I'm open to suggestions for a better method name or doc string to make its purpose clearer.

**Review by wetneb — APPROVED** [review]
