### PR TITLE
(Closes #2510) Fix the true.type() == "boolean"

### LINKED ISSUE #2510: true.type() return « java.lang.Boolean » and not « boolean »
**Describe the bug**

Expression|Result|Expected result
-- | -- | --
true.type()|**"java.lang.Boolean"**|_"boolean"_
(1).type()|"number"|"number"
"A".type()|"string"|"string"
now().type()|"date"|"date"
[].type()|"array"|"array"
null.type()|"undefined"|~~"null"~~ "undefined"

**To Reproduce**
1. Go to 'Edit cells -> Transforms…'
2. Enter 'true.type()' in the Expression field
3. See « java.lang.Boolean » in the preview

**Current Results**
true.type() -> "java.lang.Boolean"
null.type() -> "undefined"

**Expected behavior**
true.type() -> "boolean"
~~null.type() -> "null"~~

**OpenRefine (please complete the following information):**
 - Version v3.3

### PR DESCRIPTION
**Pull request by antoine2711**
(Closes #2510)
Fix the true.type() == "boolean" instead of "java.lang.Boolean".

Regards,
   Antoine

### CODE REVIEW

**Comment by antoine2711** [comment]
@weblate: I don't understand why it doesn't build. On my machine, it build fine.

Regards, Antoine

**Comment by wetneb** [comment]
@tfmorris We can squash commits when merging via GitHub's UI, I routinely do it (and I would propose to make it a default - I think we can configure this in the repository somewhere).

**Comment by tfmorris** [comment]
@wetneb I understand that, but it's an all or nothing process and sometimes there are significant commits which should be kept separate. I've got a strong preference for developers creating clean PRs which are as easy as possible for the reviewers to review without distraction.

**Comment by antoine2711** [comment]
> If the only test change was to account for the changed description, that would imply that we don't have any unit test coverage for the type functionality itself. Can you add one?

Hi @tfmorris: yes, I had the same thought. Can you point me to a file that does the same for another function, and I will base myself from that.
 
> Also, can you squash all the commits which consist of nothing but white space changes? This is small enough that a single commit makes sense.

Yes, I want to merge them. Can you point me to a documentation page on how to do that? I have no clue, I don't know Git.

Thank you for you feedback. Regards, Antoine

**Comment by wetneb** [comment]
@antoine2711 you can imitate this test class, which tests another GREL function:

`main/tests/server/src/com/google/refine/expr/functions/CoalesceTests.java`

**Comment by antoine2711** [comment]
> @antoine2711 you can imitate this test class, which tests another GREL function:
> `main/tests/server/src/com/google/refine/expr/functions/CoalesceTests.java`

Thank you for the information. So I did phase one of test units for this type function. Tell me what to add.

Regards,
   Antoine

File: main/tests/server/src/com/google/refine/expr/functions/TypeTests.java [hunk 1]
```diff
@@ -26,15 +26,84 @@
...
+    
+    @Test
+    public void testType() {
+        Assert.assertEquals(invoke("type", (Object) null),"undefined");
+        Assert.assertEquals(invoke("type", 1),"number");
+        Assert.assertEquals(invoke("type", true),"boolean");
+        Assert.assertEquals(invoke("type", "a string"),"string");
+        Assert.assertEquals(invoke("type", dateTimeValue), "date");
+        Assert.assertEquals(invoke("type", listArray), "array");
+//        Assert.assertEquals(invoke("type", error), "error");
```
Comment (wetneb) [inline main/tests/server/src/com/google/refine/expr/functions/TypeTests.java:101]: I would remove this commented out line.

File: main/src/com/google/refine/expr/functions/Type.java [hunk 2]
```diff
@@ -70,7 +72,7 @@ public Object call(Properties bindings, Object[] args) {
 
     @Override
     public String getDescription() {
-        return "Returns the type of o";
+        return "Returns the type of o as a string ('string', 'date', 'number', 'array', 'boolean', 'error' or a class name)";
```
Comment (tfmorris) [inline main/src/com/google/refine/expr/functions/Type.java:75]:
```suggestion
        return "Returns the type of o as a string ('string', 'date', 'number', 'array', or 'boolean'). The string 'error' is returned if the value can't be evaluated";
```
Now that the bug is fixed, can it ever return a Java class name? I'd be tempted to just pare this down to simply "Returns the type of o as a string."

File: main/tests/server/src/com/google/refine/expr/functions/TypeTests.java (hunk 1 above)
Comment (tfmorris) [inline main/tests/server/src/com/google/refine/expr/functions/TypeTests.java:101]:
```suggestion
```

File: main/tests/server/src/com/google/refine/expr/functions/TypeTests.java [hunk 3]
```diff
@@ -26,15 +26,84 @@
...
+    }
+    
     @Test
     public void serializeType() {
-        String json = "{\"description\":\"Returns the type of o\",\"params\":\"object o\",\"returns\":\"string\"}";
+        String json = "{\"description\":\"Returns the type of o as a string ('string', 'date', 'number', 'array', 'boolean', 'error' or a class name)\",\"params\":\"object o\",\"returns\":\"string\"}";
```
Comment (tfmorris) [inline main/tests/server/src/com/google/refine/expr/functions/TypeTests.java:106]: Fix test to match above.

Comment (antoine2711) [reply main/tests/server/src/com/google/refine/expr/functions/TypeTests.java:106]: Is what to be understood here is that type(an error) will only return "error" for certains types of errors? And if so, shouldn't it be documented which error are trap and which one are « reraised »?

Regards, Antoine

Comment (antoine2711) [reply main/tests/server/src/com/google/refine/expr/functions/TypeTests.java:106]: I also think this should be taken in consideration with PR #2562.

In particular, if `isError(aParticularValue) == true`, then `type(aParticularValue) == "error"` should be true.

Regards, A.

**Comment by wetneb** [comment]
Ok, the case where we obtain the type of an `EvalError` does not work because `type` is currently a function, not a control, so it cannot catch evaluation errors.
If the argument of a function evaluates to an error, the function call evaluates to that error again.

So we should document this properly: in the code, remove the `EvalError` case, and in the tests, add a comment saying that for now it does not work because `type` is a function and not a control.

Or you can also decide to change `type` from a function to a control in the same PR if you feel like it.

**Comment by antoine2711** [comment]
> Or you can also decide to change `type` from a function to a control in the same PR if you feel like it.

Hi @wetneb. Thank you very much for following up on this. Yes, I think that change `type()` to a control would be the best solution. 

1. It doesn't break anything;
2. It respects the original intent of the devs;
3. It make `type()` more useful as a control.

Regards, Antoine

**Comment by tfmorris** [comment]
> > Or you can also decide to change `type` from a function to a control in the same PR if you feel like it.
> Yes, I think that changing `type()` to a control would be the best solution.
> 
> 1. It doesn't break anything;

Are you sure? Doesn't that mean that `true.type()` will no longer work? Users will have to switch to `type(true)` if it's a control.

**Comment by antoine2711** [comment]
> Are you sure? Doesn't that mean that `true.type()` will no longer work? Users will have to switch to `type(true)` if it's a control.

Thanks @tfmorris for this accurate and important correction.

So, taking in account that we can't change the function's behavior with error arguments for many reasons, would it be possible/easy to code in order to:
- change type() to a control, but also implement the .dot.function() feature;
- or change the behavior of every control by implementing the .dot.function() feature for every control. It would be nice to be able to be able to write: `true.if(eTrueExpr, eFalseExpr)`… It could help making the reading of GREL's code easier.

What would be the other pros and cons of these two options?

Regards,
   Antoine

**Comment by ostephens** [comment]
I'm in favour of looking at allowing the dot syntax for controls, but it probably needs working through carefully to check it doesn't break anything. I'd suggest we keep this PR to its original scope (and improvements to .type() are welcome after all even if there are some cases where it doesn't work), and tackle changes to controls separately

**Comment by antoine2711** [comment]
> I'm in favour of looking at allowing the dot syntax for controls, but it probably needs working through carefully to check it doesn't break anything. I'd suggest we keep this PR to its original scope (and improvements to .type() are welcome after all even if there are some cases where it doesn't work), and tackle changes to controls separately

Hi @ostephens, thank you for your feedback.

So, I created an issue: « Extending the dot syntax for controls #2618 ». Also, for the `type()` function not returning "error", I created last month an issue just on that subject « type(an error) should return the string "error" like the code was designed to do but is buggy #2562 », but no one responded/contributed. I will do a summary there of what we've discussed here.

Regards,
   Antoine

File: main/src/com/google/refine/expr/functions/Type.java (hunk 2 above)
Comment (antoine2711) [reply main/src/com/google/refine/expr/functions/Type.java:75]: > Now that the bug is fixed, can it ever return a Java class name? I'd be tempted to just pare this down to simply "Returns the type of o as a string."

@tfmorris: the question you raise is far more complex, from what I see. In Issue « 
true.type() return « java.lang.Boolean » and not « boolean »
#2510 », you will find some discussion on that, but here's a table I did:
Expression|Result|Expected result
--- | -- | :------:
row.type()|com.google.refine.expr.WrappedRow|"object: row" 
row.record.type()| com.google.refine.expr.WrappedRow$WrappedRecord |"object: record"
cell.type()| com.google.refine.expr.WrappedCell |"object: cell"
cells.type()| com.google.refine.expr.CellTuple |"object: cells"
cell.recon.features.type()| com.google.refine.model.Recon$Features |"object: features"
row.record.cells.type()| com.google.refine.expr.WrappedRow$RecordCells |"object: cells"

Because in the code, we have this: `return v.getClass().getName()`, we can never be sure of all the value that can be returned. I guess the only thing we can be sure it's that it's going to be a string…
```
                } else if (v instanceof EvalError) {
                    return "error";
                } else {
                    return v.getClass().getName();
                }
```
I think we should close this issue, and maybe open another one on how to return a type from an object. But closing this issue, we finalize the type() function with basic datatypes.

For this particular change you suggest: « The string 'error' is returned if the value can't be evaluated"; », I wouldn't write that because I don't believe it's accurate. Imagine the case of use `type(value)`, where value contains a previous stored error. But this discussion should be in issue « type(an error) should return the string "error" like the code was designed to do but is buggy #2562 ». Do you share this opinion?

Regards, Antoine

File: main/tests/server/src/com/google/refine/expr/functions/TypeTests.java (hunk 1 above)
Comment (antoine2711) [reply main/tests/server/src/com/google/refine/expr/functions/TypeTests.java]: Done.

Comment (antoine2711) [reply main/tests/server/src/com/google/refine/expr/functions/TypeTests.java]: Done.

**Comment by antoine2711** [comment]
@tfmorris: 
So, the last question standing in this issue is:
« String json = "{\"description\":\"Returns the type of o as a string ('string', 'date', 'number', 'array', 'boolean', 'error' or a class name)\",\"params\":\"object o\",\"returns\":\"string\"}"; »

I've remove the "error" test, like you asked.

I think we should keep it like this, deal with 'error' in Issue #2562, deal with object class name in a new issue, and close this issue. But if you insist on changing the description, I will go in your path.

Regards,
   Antoine

**Comment by wetneb** [comment]
I think it would be cleaner to:
- remove the `EvalError` branch in the function - at the moment this is dead code. We can replace it by a comment explaining that we would like to add support for this, but it requires changing `type` into a control (with a link to the issue)
- update the description, to remove the mention of the `error` value, since it cannot be returned

These things will be easy to add back once #2562 is tackled.

**Comment by antoine2711** [comment]
> * remove the `EvalError` branch in the function - at the moment this is dead code. We can replace it by a comment explaining that we would like to add support for this, but it requires changing `type` into a control (with a link to the issue)
> * update the description, to remove the mention of the `error` value, since it cannot be returned

Done. Added this text: `// @ToDo fix this with issue #2562` and the two lines where commented.

Anything else before merging this PR?

Regards,
   Antoine

File: main/src/com/google/refine/expr/functions/Type.java (hunk 2 above)
Comment (tfmorris) [reply main/src/com/google/refine/expr/functions/Type.java]: Marking this as resolved. As discussed elsewhere, evaluation errors happen before ever reaching this function.
