### PR TITLE
Fix recon deserialization error for matched cells

### LINKED ISSUE #6464: Impossible to load a project again after manually matching reconciled cells with errors
In some circumstances it is possible that loading a previously saved project fails in 3.8-beta1.

### To Reproduce
1. First, reconcile a column to a reconciliation service that returns errors
2. Then, manually match some cell with an error to an entity
3. Close OpenRefine
4. Start OpenRefine and open the project again

### Current Results

The project does not load and logs show:

```
com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.google.refine.model.Recon`, problem: there is a match hence no error
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 445]
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:2014)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:598)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:621)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:293)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:301)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:445)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1493)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:348)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4899)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3846)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3814)
	at com.google.refine.model.Recon.loadStreaming(Recon.java:392)
	at com.google.refine.util.Pool.load(Pool.java:151)
	at com.google.refine.util.Pool.load(Pool.java:118)
	at com.google.refine.io.ProjectUtilities.loadFromFile(ProjectUtilities.java:153)
	at com.google.refine.io.ProjectUtilities.load(ProjectUtilities.java:118)
	at com.google.refine.io.FileProjectManager.loadProject(FileProjectManager.java:245)
	at com.google.refine.ProjectManager.getProject(ProjectManager.java:555)
```

### Expected Behavior

The project should be loaded again in the state it was left in.

### Additional context

This is due to the checks we have introduced in the deserialization of Recon objects, which assume that a recon object cannot both be matched to an entity and contain an error.

When matching a cell with a reconciliation error to an entity, we do not currently discard the error it contains, leading to this inconsistency.

I would argue that we should in fact keep the error, so that if we unmatch the cell, we get back to the original state of the cell after reconciliation, containing the original error.
I would propose to change the "invariant" that we try to enforce in the Recon class, to be that a Recon object cannot contain an error and a non-empty list of candidates at the same time.

As a side note, this bug would not have been allowed to happen if the Recon class had been immutable, making sure that any "changes" require going through a new constructor call which is allowed to check consistency of all fields. As an initial remediation we could already use encapsulation with setters to modify fields, making it possible to control which changes are allowed.

cc @ayushrai206

### PR DESCRIPTION
**Pull request by wetneb**
Closes #6464.

### CODE REVIEW

**Review by ayushrai206 — APPROVED** [review]
I am surprised that I didn't catch this earlier! I went through the changes, go with them !

File: main/src/com/google/refine/model/Recon.java [hunk 1]
```diff
@@ -412,11 +413,11 @@ public Recon(
         this.judgment = judgment != null ? judgment : Judgment.None;
         this.match = match;
         this.error = error;
-        if (error != null && match != null) {
-            throw new IllegalArgumentException("there is a match hence no error");
-        }
         this.features = features != null ? features : new Object[Feature_max];
         this.candidates = candidates != null ? candidates : new ArrayList<>();
+        if (error != null && !this.candidates.isEmpty()) {
+            throw new IllegalArgumentException("Recon deserialization: there are candidates hence no error");
```
Comment (tfmorris) [inline main/src/com/google/refine/model/Recon.java:419]:
```suggestion
            throw new IllegalArgumentException("Recon deserialization: inconsistent state - error & candidates not allowed together");
```
