### PR TITLE
Fix type of error message returned by the Filter GREL control

### LINKED ISSUE #6694: Filter() control returns text string not error object when first argument is not an array
Compare the code for Filter
https://github.com/OpenRefine/OpenRefine/blob/05978a07fa8cdca0dc356233b178ef85d76c1676/main/src/com/google/refine/grel/controls/Filter.java#L70

to equivalent code in ForEach
https://github.com/OpenRefine/OpenRefine/blob/05978a07fa8cdca0dc356233b178ef85d76c1676/main/src/com/google/refine/grel/controls/ForEach.java#L74

Filter should return an eval error not a string at this point so it can be caught appropriately in GREL / UI

### PR DESCRIPTION
**Pull request by sunil-atheer**
Filter class argument type mismatch

Fixes #6694 

Changes proposed in this pull request:
- Filter class now returns proper error if the argument is invalid
- Updated Filter test for params validation

### CODE REVIEW

**Comment by sunil-atheer** [comment]
@wetneb Can you review the fix

File: main/resources/com/google/refine/grel/ControlEvalError.properties [hunk 1]
```diff
@@ -13,3 +13,4 @@ expects_second_arg_var_name={0} expects second argument to be a variable name
 expects_second_arg_index_var_name={0} expects second argument to be the index's variable name
 expects_third_arg_element_var_name={0} expects second argument to be the element's variable name
 expects_second_third_args_different={0} expects the second and third arguments to be different variable names
+expects_array_arg={0} is not an array
```
Comment (wetneb) [inline main/resources/com/google/refine/grel/ControlEvalError.properties:16]: I wouldn't introduce a new translation string: why not keep the existing one? It does not seem to be used anywhere so you can modify it as you wish.
Looking at the pattern of the error messages around it, I would suggest something like `{0} expects an array as its first argument`, where `{0}` gets replaced by the function name, not the value.

**Review by wetneb — CHANGES_REQUESTED** [review]
Thank you for this contribution!

**Comment by ostephens** [comment]
> Filter class argument type mismatch
> 
> Fixes #{issue number here}
> 
> ## Changes proposed in this pull request:

@sunil-atheer when you do a PR it helps if you fill out the details in the template as should here. Including the issue number here (rather than just in the title) will mean that GitHub automatically links together the issue and the PR, and summarising the changes is helpful (although very brief for a small request like this) so those reviewing understand what you are doing before looking at the detail in the code

**Comment by ostephens** [comment]
I'd suggest that this PR could be a good opportunity to expand test coverage for the `filter` function to include tests for invalid parameter behaviour.

Filter tests are in https://github.com/OpenRefine/OpenRefine/blob/master/main/tests/server/src/com/google/refine/grel/controls/FilterTests.java
See forEach tests for example of how to test for behaviour on invalid parameters https://github.com/OpenRefine/OpenRefine/blob/c4b0847e1f61952c1ce55dd37036aa3a56f08c51/main/tests/server/src/com/google/refine/grel/controls/ForEachTests.java#L59

File: main/resources/com/google/refine/grel/ControlEvalError.properties (hunk 1 above)
Comment (ostephens) [reply main/resources/com/google/refine/grel/ControlEvalError.properties:16]: @wetneb That was my initial thought too. However I think it might be the case that `filter` actually accepts the same types for the first argument as `forEach` and `forEachIndex`. If this could be verified, then having a new translation string like proposed here and using it for all cases could make sense?

**Comment by wetneb** [comment]
@sunil-atheer I encourage you to edit the description of your pull request, following @ostephens' advice. In the meantime I am changing the PR title already, so that it is more informative. That helps people understand what the pull request does, for instance when looking at [the list of our open pull requests](https://github.com/OpenRefine/OpenRefine/pulls).

File: main/resources/com/google/refine/grel/ControlEvalError.properties [hunk 2]
```diff
@@ -13,4 +13,4 @@ expects_second_arg_var_name={0} expects second argument to be a variable name
 expects_second_arg_index_var_name={0} expects second argument to be the index's variable name
 expects_third_arg_element_var_name={0} expects second argument to be the element's variable name
 expects_second_third_args_different={0} expects the second and third arguments to be different variable names
-expects_array_arg={0} is not an array
\ No newline at end of file
+expects_array_arg={0} expects an array as its first argument
```
Comment (ostephens) [inline main/resources/com/google/refine/grel/ControlEvalError.properties:16]: For consistency with other properties here I'd suggest naming this `expects_first_arg_array` (in case later need to have a similar constraint on a second or third argument etc.)

File: main/tests/server/src/com/google/refine/grel/controls/FilterTests.java [hunk 3]
```diff
@@ -27,15 +27,48 @@
...
+        Object result = eval.evaluate(bindings);
+        assertTrue(result instanceof EvalError, "Expression didn't return error : " + expression);
+    }
+
+    @Test
+    public void testInvalidParams() throws ParsingException {
+        bindings = new Properties();
+        bindings.put("v", "");
+        assertParseError("filter('test', v, v)");
+        try {
```
Comment (ostephens) [inline main/tests/server/src/com/google/refine/grel/controls/FilterTests.java:63]: I think you could include a test for the use of the variable here as well (can be seen in foreach tests like `assertParseError("forEach([], 1, 1)");)`

File: main/tests/server/src/com/google/refine/grel/controls/FilterTests.java [hunk 4]
```diff
@@ -27,15 +27,48 @@
...
+        Evaluable eval = MetaParser.parse("grel:" + expression);
+        Object result = eval.evaluate(bindings);
+        assertTrue(result instanceof EvalError, "Expression didn't return error : " + expression);
+    }
+
+    @Test
+    public void testInvalidParams() throws ParsingException {
+        bindings = new Properties();
+        bindings.put("v", "");
+        assertParseError("filter('test', v, v)");
```
Comment (ostephens) [inline main/tests/server/src/com/google/refine/grel/controls/FilterTests.java:62]: I think this should also be wrapped in a try/throw in order for us to check both that the first argument is rejected because it's not an array, and the catch so we check that the result of that is that we throw an EvalError rather than a string?

Note this doesn't seem to have been done in forEach but I think it's the right thing to do
@wetneb am I right?

**Review by ostephens — CHANGES_REQUESTED** [review]

File: main/tests/server/src/com/google/refine/grel/controls/FilterTests.java (hunk 3 above)
Comment (sunil-atheer) [reply main/tests/server/src/com/google/refine/grel/controls/FilterTests.java:63]: I did not include this as the 3rd arg is used if its a boolean

File: main/resources/com/google/refine/grel/ControlEvalError.properties (hunk 2 above)
Comment (sunil-atheer) [reply main/resources/com/google/refine/grel/ControlEvalError.properties:16]: Updated key

File: main/tests/server/src/com/google/refine/grel/controls/FilterTests.java (hunk 4 above)
Comment (wetneb) [reply main/tests/server/src/com/google/refine/grel/controls/FilterTests.java:62]: Intuitively, rejecting the first argument because it's not array should not throw an exception at parsing stage, it should return an EvalError at evaluation stage, so there shouldn't be a need for a try/catch here.
Besides, to check that something throws an exception it's better to use `assertThrows()` as it makes the assertion clearer and the code simpler.

Comment (wetneb) [reply main/tests/server/src/com/google/refine/grel/controls/FilterTests.java:62]: No need to clean up the existing ones as I have a pull request open to address that: https://github.com/OpenRefine/OpenRefine/pull/6645. But it's helpful if you can use `assertThrows` for any new assertions you are making.

File: main/tests/server/src/com/google/refine/grel/controls/FilterTests.java (hunk 3 above)
Comment (ostephens) [reply main/tests/server/src/com/google/refine/grel/controls/FilterTests.java:63]: But we can still test that the second argument is a variable here?

Comment (sunilnatraj) [reply main/tests/server/src/com/google/refine/grel/controls/FilterTests.java:63]: Added test case for this.

**Review by ostephens — APPROVED** [review]

**Review by sunilnatraj — APPROVED** [review]

File: main/tests/server/src/com/google/refine/grel/controls/FilterTests.java [hunk 5]
```diff
@@ -27,15 +27,53 @@
...
+        try {
+            assertParseError("filter([], 1, 1)");
+            fail("Didn't throw a ParsingException for wrong argument type");
+        } catch (ParsingException e) {
+        }
```
Comment (wetneb) [inline main/tests/server/src/com/google/refine/grel/controls/FilterTests.java:67]: As mentioned in my earlier comment, it is better if you can use `assertThrows` to assert that a particular piece of code throws an exception. Here is an example to help you understand what it would look like:
```suggestion
        assertThrows("Didn't throw a ParsingException for wrong argument type", ParsingException.class,
                () -> MetaParser.parse("grel:filter([], 1, 1)"));
```
Because the error is coming from the parsing stage, not the evaluation stage, we can make the assertion narrower by calling the parser only and checking that it does throw.

Would you be able to adapt the rest of the test following this pattern?

**Review by wetneb — CHANGES_REQUESTED** [review]

File: main/tests/server/src/com/google/refine/grel/controls/FilterTests.java (hunk 5 above)
Comment (sunilnatraj) [reply main/tests/server/src/com/google/refine/grel/controls/FilterTests.java]: @wetneb I updated all the cases to use assertThrows

File: main/tests/server/src/com/google/refine/grel/controls/FilterTests.java [hunk 6]
```diff
@@ -27,15 +27,53 @@
...
-public class FilterTests {
+public class FilterTests extends GrelTestBase {
 
     @Test
     public void serializeFilter() {
         String json = "{\"description\":\"Evaluates expression a to an array. Then for each array element, binds its value to variable name v, evaluates expression test which should return a boolean. If the boolean is true, pushes v onto the result array.\",\"params\":\"expression a, variable v, expression test\",\"returns\":\"array\"}";
         TestUtils.isSerializedTo(new Filter(), json);
     }
+
+    private void assertParseError(String expression) throws ParsingException {
```
[the remark this answers is not in the document]
Comment (sunilnatraj) [reply main/tests/server/src/com/google/refine/grel/controls/FilterTests.java]: @wetneb As the 1st case is a positive case; i updated the name of the function and its working

[the remark this answers is not in the document]
Comment (wetneb) [reply main/tests/server/src/com/google/refine/grel/controls/FilterTests.java]: Well, now this first case does not assert that the returned value is an `EvalError` anymoe, which I think would be worth doing. So I would add back this assertion and change the name of this method to `assertEvaluatesToError`, again.

You seem to be unclear on the distinction between a parse error and an evaluation error. Let me try to explain this distinction with an analogy: instead of talking about GREL expressions, let's talk about sentences in English.
Consider the following sentences:
1. "The moon satellite a is of Elvis Presley." - > this sentence is syntactically incorrect: it has a parse error, because the words are in an incorrect order
2. "The moon is a satellite of Elvis Presley." -> this sentence is syntactically correct, but it does not make sense: humans don't have satellites.
3. "The moon is a satellite of the Earth." -> this sentence is syntactically correct, and its meaning is true.

As you can see in those examples, sentences in English can have (at least) two sorts of problems:
1. being syntactically incorrect: that means that their structure does not respect the grammar of the language
2. being semantically wrong: that means that although their structure respects the rules of the language, they don't make sense

Similarly, in GREL, expressions can have two sorts of problems:
* a syntax error, meaning that they do not conform to the grammar of GREL. In this case, `ParsingException` is thrown
* an evaluation error: meaning that although they could be parsed successfully (without throwing a `ParsingException`), evaluating them returns an `EvalError`

When writing tests for this, it is important that this distinction is clear so that you can correctly assert whether a `ParsingException` is thrown at the parsing stage or an `EvalError` is returned at the evaluation stage.

[the remark this answers is not in the document]
Comment (sunilnatraj) [reply main/tests/server/src/com/google/refine/grel/controls/FilterTests.java]: @wetneb Thanks for the explanation; i missed the Evaluation error case. I have updated the function. Please review

**Review by wetneb — APPROVED** [review]

**Comment by sunilnatraj** [comment]
@wetneb  All approvals are in place and tests have passed. Who will merge the PR

**Comment by sunilnatraj** [comment]
@wetneb  All approvals are in place and tests have passed. Who will merge the PR

**Comment by sunilnatraj** [comment]
Thank you @wetneb @ostephens
