### PR TITLE
Fix NPE bug in EditInspector

### LINKED ISSUE #3354: Unable to make schema for own Wikibase: NullPointerException in EditInspector
### To Reproduce
1. Setup a Wikibase instance with a query service and openrefine
2. Use the query service to download some data (https://tinyurl.com/y5xmdjtw)
3. Try to create a schema to save the (updated) data back

The manifest I am using for testing is:
```
{
  "version": "1.0",
  "mediawiki": {
    "name": "Nimiarkisto (dev)",
    "root": "https://nimiarkisto.nikerabb.it/wiki/",
    "main_page": "https://nimiarkisto.nikerabb.it",
    "api": "https://nimiarkisto.nikerabb.it/w/api.php"
  },
  "wikibase": {
    "site_iri": "http://nimiarkisto.fi/entity/",
    "maxlag": 5,
    "properties": {
      "instance_of": "P31",
      "subclass_of": "P3"
    }
  },
  "oauth": {
    "registration_page": "https://nimiarkisto.nikerabb.it/wiki/Special:OAuthConsumerRegistration/propose"
  },
  "reconciliation": {
    "endpoint": "https://nimiarkisto.nikerabb.it/reconciliation/${lang}/api"
  }
}
```

### Current Results
"Issues" tab is completely empty.
"Preview tab" says:
> This tab shows the first edits (out of 0) that will be made once you upload the changes to Nimiarkisto (dev). You can use facets to inspect the edits on particular items.

Choosing "Upload edits to Wikibase" just briefly shows "Analyzing" popup and displays the "Schema tab".

From OpenRefine logs:
```
openrefine_1        | 16:54:12.836 [                   refine] GET /command/core/get-csrf-token (11552ms)
openrefine_1        | 16:54:12.942 [                   refine] POST /command/wikidata/preview-wikibase-schema (106ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [FormatScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (4ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [InverseConstraintScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [UnsourcedScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [RestrictedPositionScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [QualifierCompatibilityScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [SingleValueScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [DistinctValuesScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [QuantityScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [RestrictedValuesScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [EntityTypeScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [MultiValueScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [DifferenceWithinRangeScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [ConflictsWithScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [ItemRequiresScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [UseAsQualifierScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [                  command] Exception caught (0ms)
openrefine_1        | java.lang.NullPointerException
openrefine_1        |   at org.openrefine.wikidata.qa.EditInspector.inspect(EditInspector.java:127)
openrefine_1        |   at org.openrefine.wikidata.commands.PreviewWikibaseSchemaCommand.doPost(PreviewWikibaseSchemaCommand.java:110)
openrefine_1        |   at com.google.refine.RefineServlet.service(RefineServlet.java:187)
openrefine_1        |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
openrefine_1        |   at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
openrefine_1        |   at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
openrefine_1        |   at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
openrefine_1        |   at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
openrefine_1        |   at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
openrefine_1        |   at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
openrefine_1        |   at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
openrefine_1        |   at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
openrefine_1        |   at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
openrefine_1        |   at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
openrefine_1        |   at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
openrefine_1        |   at org.mortbay.jetty.Server.handle(Server.java:326)
openrefine_1        |   at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
openrefine_1        |   at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
openrefine_1        |   at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
openrefine_1        |   at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
openrefine_1        |   at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
openrefine_1        |   at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
openrefine_1        |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
openrefine_1        |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
openrefine_1        |   at java.lang.Thread.run(Thread.java:748)
```
If I use "Export Schema" from the "Extensions: Wikidata" dropdown, it gives this:
```
{
   "itemDocuments":[
      {
         "subject":{
            "type":"wbitemvariable",
            "columnName":"nimilippu"
         },
         "nameDescs":[
            
         ],
         "statementGroups":[
            {
               "property":{
                  "type":"wbpropconstant",
                  "pid":"P10020",
                  "label":"image",
                  "datatype":"external-id"
               },
               "statements":[
                  {
                     "value":{
                        "type":"wbstringvariable",
                        "columnName":"kuvapolku"
                     },
                     "qualifiers":[
                        
                     ],
                     "references":[
                        
                     ]
                  }
               ]
            }
         ]
      }
   ],
   "siteIri":"http://nimiarkisto.fi/entity/",
   "mediaWikiApiEndpoint":"https://nimiarkisto.nikerabb.it/w/api.php"
}
```

### Expected Behavior
To see items on the preview tab.

### Screenshots
Schema tab

### Versions
 - Operating System: Debian 10
 - Browser Version: Google Chrome 87.0.4280.66
 - JRE or JDK Version: openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
 - OpenRefine: Version 3.5-beta [528f4a4]

### Datasets
See https://tinyurl.com/y5xmdjtw for the data I'm trying to use

### PR DESCRIPTION
**Pull request by afkbrb**
Close #3354

### CODE REVIEW

File: extensions/wikidata/src/org/openrefine/wikidata/qa/EditInspector.java [hunk 1]
```diff
@@ -124,7 +123,6 @@ public void inspect(List<ItemUpdate> editBatch, WikibaseSchema schema) throws Ex
         // so that all newly created entities appear in the batch
         SchemaPropertyExtractor fetcher = new SchemaPropertyExtractor();
         Set<PropertyIdValue> properties = fetcher.getAllProperties(schema);
-        List<EntityDocument> propertyDocuments = entityCache.getMultipleDocuments(properties.stream().collect(Collectors.toList()));
```
Comment (wetneb) [inline extensions/wikidata/src/org/openrefine/wikidata/qa/EditInspector.java:127]: This was added by @darecoder to prefetch property documents in one API call rather than requesting them one by one. I assume your IDE detected that the `propertyDocuments` variable was not used later on. I think we should just call `getMultipleDocuments` without storing the return result in a local variable. It would be good to have a comment here explaining why we are doing that.

**Review by wetneb — COMMENTED** [review]
Thank you so much, that was lightning-fast!

File: extensions/wikidata/src/org/openrefine/wikidata/qa/EditInspector.java (hunk 1 above)
Comment (afkbrb) [reply extensions/wikidata/src/org/openrefine/wikidata/qa/EditInspector.java:127]: Got it!

**Review by wetneb — APPROVED** [review]
